// transit-js 0.8.757
// http://transit-format.org
// 
// Copyright 2014 Cognitect. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License..
;(function(){function aa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var d=Object.prototype.toString.call(a);if("[object Window]"==d)return"object";if("[object Array]"==d||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==d||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};function c(a,b){this.A=a|0;this.p=b|0}var ba={};function l(a){if(-128<=a&&128>a){var b=ba[a];if(b)return b}b=new c(a|0,0>a?-1:0);-128<=a&&128>a&&(ba[a]=b);return b}function m(a){return isNaN(a)||!isFinite(a)?n:a<=-ca?p:a+1>=ca?da:0>a?r(m(-a)):new c(a%t|0,a/t|0)}function u(a,b){return new c(a,b)}
function v(a,b){if(0==a.length)throw Error("number format error: empty string");var d=b||10;if(2>d||36<d)throw Error("radix out of range: "+d);if("-"==a.charAt(0))return r(v(a.substring(1),d));if(0<=a.indexOf("-"))throw Error('number format error: interior "-" character: '+a);for(var e=m(Math.pow(d,8)),f=n,g=0;g<a.length;g+=8){var h=Math.min(8,a.length-g),k=parseInt(a.substring(g,g+h),d);8>h?(h=m(Math.pow(d,h)),f=f.multiply(h).add(m(k))):(f=f.multiply(e),f=f.add(m(k)))}return f}
var t=4294967296,ca=t*t/2,n=l(0),w=l(1),ea=l(-1),da=u(-1,2147483647),p=u(0,-2147483648),fa=l(16777216);function x(a){return a.p*t+(0<=a.A?a.A:t+a.A)}
c.prototype.toString=function(a){a=a||10;if(2>a||36<a)throw Error("radix out of range: "+a);if(z(this))return"0";if(0>this.p){if(this.equals(p)){var b=m(a),d=A(this,b),b=B(d.multiply(b),this);return d.toString(a)+b.A.toString(a)}return"-"+r(this).toString(a)}for(var d=m(Math.pow(a,6)),b=this,e="";;){var f=A(b,d),g=B(b,f.multiply(d)).A.toString(a),b=f;if(z(b))return g+e;for(;6>g.length;)g="0"+g;e=""+g+e}};function z(a){return 0==a.p&&0==a.A}
c.prototype.equals=function(a){return this.p==a.p&&this.A==a.A};c.prototype.compare=function(a){if(this.equals(a))return 0;var b=0>this.p,d=0>a.p;return b&&!d?-1:!b&&d?1:0>B(this,a).p?-1:1};function r(a){return a.equals(p)?p:u(~a.A,~a.p).add(w)}c.prototype.add=function(a){var b=this.p>>>16,d=this.p&65535,e=this.A>>>16,f=a.p>>>16,g=a.p&65535,h=a.A>>>16,k;k=0+((this.A&65535)+(a.A&65535));a=0+(k>>>16);a+=e+h;e=0+(a>>>16);e+=d+g;d=0+(e>>>16);d=d+(b+f)&65535;return u((a&65535)<<16|k&65535,d<<16|e&65535)};
function B(a,b){return a.add(r(b))}
c.prototype.multiply=function(a){if(z(this)||z(a))return n;if(this.equals(p))return 1==(a.A&1)?p:n;if(a.equals(p))return 1==(this.A&1)?p:n;if(0>this.p)return 0>a.p?r(this).multiply(r(a)):r(r(this).multiply(a));if(0>a.p)return r(this.multiply(r(a)));if(0>this.compare(fa)&&0>a.compare(fa))return m(x(this)*x(a));var b=this.p>>>16,d=this.p&65535,e=this.A>>>16,f=this.A&65535,g=a.p>>>16,h=a.p&65535,k=a.A>>>16;a=a.A&65535;var E,q,y,ma;ma=0+f*a;y=0+(ma>>>16);y+=e*a;q=0+(y>>>16);y=(y&65535)+f*k;q+=y>>>16;
y&=65535;q+=d*a;E=0+(q>>>16);q=(q&65535)+e*k;E+=q>>>16;q&=65535;q+=f*h;E+=q>>>16;q&=65535;E=E+(b*a+d*k+e*h+f*g)&65535;return u(y<<16|ma&65535,E<<16|q)};
function A(a,b){if(z(b))throw Error("division by zero");if(z(a))return n;if(a.equals(p)){if(b.equals(w)||b.equals(ea))return p;if(b.equals(p))return w;var d;d=1;if(0==d)d=a;else{var e=a.p;d=32>d?u(a.A>>>d|e<<32-d,e>>d):u(e>>d-32,0<=e?0:-1)}d=A(d,b).shiftLeft(1);if(d.equals(n))return 0>b.p?w:ea;e=B(a,b.multiply(d));return d.add(A(e,b))}if(b.equals(p))return n;if(0>a.p)return 0>b.p?A(r(a),r(b)):r(A(r(a),b));if(0>b.p)return r(A(a,r(b)));for(var f=n,e=a;0<=e.compare(b);){d=Math.max(1,Math.floor(x(e)/
x(b)));for(var g=Math.ceil(Math.log(d)/Math.LN2),g=48>=g?1:Math.pow(2,g-48),h=m(d),k=h.multiply(b);0>k.p||0<k.compare(e);)d-=g,h=m(d),k=h.multiply(b);z(h)&&(h=w);f=f.add(h);e=B(e,k)}return f}c.prototype.shiftLeft=function(a){a&=63;if(0==a)return this;var b=this.A;return 32>a?u(b<<a,this.p<<a|b>>>32-a):u(0,b<<a-32)};function ga(a,b){b&=63;if(0==b)return a;var d=a.p;return 32>b?u(a.A>>>b|d<<32-b,d>>>b):32==b?u(d,0):u(d>>>b-32,0)};var C={g:{}};C.g.N="undefined"!=typeof Object.keys?function(a){return Object.keys(a)}:function(a){var b=[],d=0,e;for(e in a)b[d++]=e;return b};C.g.isArray="undefined"!=typeof Array.isArray?function(a){return Array.isArray(a)}:function(a){return"array"===aa(a)};C.g.Ea="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";C.g.Na=function(a){return Math.round(Math.random()*a)};C.g.q=function(){return C.g.Na(15).toString(16)};
C.g.randomUUID=function(){var a=(8|3&C.g.Na(14)).toString(16);return C.g.q()+C.g.q()+C.g.q()+C.g.q()+C.g.q()+C.g.q()+C.g.q()+C.g.q()+"-"+C.g.q()+C.g.q()+C.g.q()+C.g.q()+"-4"+C.g.q()+C.g.q()+C.g.q()+"-"+a+C.g.q()+C.g.q()+C.g.q()+"-"+C.g.q()+C.g.q()+C.g.q()+C.g.q()+C.g.q()+C.g.q()+C.g.q()+C.g.q()+C.g.q()+C.g.q()+C.g.q()+C.g.q()};
C.g.btoa=function(a){if("undefined"!=typeof btoa)return btoa(a);a=String(a);for(var b,d,e=0,f=C.g.Ea,g="";a.charAt(e|0)||(f="=",e%1);g+=f.charAt(63&b>>8-e%1*8)){d=a.charCodeAt(e+=.75);if(255<d)throw Error("'btoa' failed: The string to be encoded contains characters outside of the Latin1 range.");b=b<<8|d}return g};
C.g.atob=function(a){if("undefined"!=typeof atob)return atob(a);a=String(a).replace(/=+$/,"");if(1==a.length%4)throw Error("'atob' failed: The string to be decoded is not correctly encoded.");for(var b=0,d,e,f=0,g="";e=a.charAt(f++);~e&&(d=b%4?64*d+e:e,b++%4)?g+=String.fromCharCode(255&d>>(-2*b&6)):0)e=C.g.Ea.indexOf(e);return g};C.g.Xa=function(a){for(var b=0,d=a.length,e="",f=null;b<d;)f=a.subarray(b,Math.min(b+32768,d)),e+=String.fromCharCode.apply(null,f),b+=32768;return C.g.btoa(e)};
C.g.Qa=function(a){a=C.g.atob(a);for(var b=a.length,d=new Uint8Array(b),e=0;e<b;e++)d[e]=a.charCodeAt(e);return d};C.l={};C.l.D="~";C.l.Wa="#";C.l.Z="^";C.l.Ba="`";C.l.S="~#";C.a={};C.a.na="transit$hashCode$";C.a.Ha=1;C.a.equals=function(a,b){if(null==a)return null==b;if(a===b)return!0;if("object"===typeof a){if(C.g.isArray(a)){if(C.g.isArray(b)&&a.length===b.length){for(var d=0;d<a.length;d++)if(!C.a.equals(a[d],b[d]))return!1;return!0}return!1}if(a.G)return a.G(b);if(null!=b&&"object"===typeof b){if(b.G)return b.G(a);var d=0,e=C.g.N(b).length,f;for(f in a)if(a.hasOwnProperty(f)&&(d++,!b.hasOwnProperty(f)||!C.a.equals(a[f],b[f])))return!1;return d===e}}return!1};
C.a.oa=function(a,b){return a^b+2654435769+(a<<6)+(a>>2)};C.a.wa={};C.a.xa=0;C.a.Va=256;C.a.jb=function(a){var b=C.a.wa[a];if(null!=b)return b;for(var d=b=0;d<a.length;++d)b=31*b+a.charCodeAt(d),b%=4294967296;C.a.xa++;C.a.xa>=C.a.Va&&(C.a.wa={},C.a.xa=1);return C.a.wa[a]=b};
C.a.hashMapLike=function(a){var b=0;if(null!=a.forEach)a.forEach(function(a,d){b=(b+(C.a.j(d)^C.a.j(a)))%4503599627370496});else for(var d=C.g.N(a),e=0;e<d.length;e++)var f=d[e],g=a[f],b=(b+(C.a.j(f)^C.a.j(g)))%4503599627370496;return b};C.a.hashArrayLike=function(a){var b=0;if(C.g.isArray(a))for(var d=0;d<a.length;d++)b=C.a.oa(b,C.a.j(a[d]));else a.forEach&&a.forEach(function(a){b=C.a.oa(b,C.a.j(a))});return b};
C.a.j=function(a){if(null==a)return 0;switch(typeof a){case "number":return a;case "boolean":return!0===a?1:0;case "string":return C.a.jb(a);case "function":var b=a[C.a.na];b||(b=C.a.Ha,"undefined"!=typeof Object.defineProperty?Object.defineProperty(a,C.a.na,{value:b,enumerable:!1}):a[C.a.na]=b,C.a.Ha++);return b;default:return a instanceof Date?a.valueOf():C.g.isArray(a)?C.a.hashArrayLike(a):a.I?a.I():C.a.hashMapLike(a)}};C.a.extendToEQ=function(a,b){a.I=b.hashCode;a.G=b.equals;return a};C.types={};function D(a,b){this.tag=a;this.rep=b;this.j=-1}D.prototype.toString=function(){return"[TaggedValue: "+this.tag+", "+this.rep+"]"};D.prototype.L=function(a){return C.a.equals(this,a)};D.prototype.equiv=D.prototype.L;D.prototype.G=function(a){return a instanceof D?this.tag===a.tag&&C.a.equals(this.rep,a.rep):!1};D.prototype.I=function(){-1===this.j&&(this.j=C.a.oa(C.a.j(this.tag),C.a.j(this.rep)));return this.j};C.types.K=function(a,b){return new D(a,b)};
C.types.isTaggedValue=function(a){return a instanceof D};C.types.yb=function(){return null};C.types.Ya=function(a){return"t"===a};C.types.Sa=v("9007199254740992");C.types.Ta=v("-9007199254740992");C.types.Ja=function(a){if("number"===typeof a||a instanceof c)return a;a=v(a,10);return 0<a.compare(C.types.Sa)||0>a.compare(C.types.Ta)?a:x(a)};c.prototype.L=function(a){return C.a.equals(this,a)};c.prototype.equiv=c.prototype.L;c.prototype.G=function(a){return a instanceof c&&this.equals(a)};
c.prototype.I=function(){return this.A};C.types.isInteger=function(a){return a instanceof c?!0:"number"===typeof a&&!isNaN(a)&&Infinity!==a&&parseFloat(a)===parseInt(a)};C.types.ib=function(a){return parseFloat(a)};C.types.Da=function(a){return C.types.K("n",a)};C.types.mb=function(a){return a instanceof D&&"n"===a.tag};function ha(a){return C.types.K("f",a)}C.types.lb=function(a){return a instanceof D&&"f"===a.tag};C.types.$a=function(a){return a};function F(a){this.name=a;this.j=-1}
F.prototype.toString=function(){return":"+this.name};F.prototype.L=function(a){return C.a.equals(this,a)};F.prototype.equiv=F.prototype.L;F.prototype.G=function(a){return a instanceof F&&this.name==a.name};F.prototype.I=function(){-1===this.j&&(this.j=C.a.j(this.name));return this.j};C.types.keyword=function(a){return new F(a)};C.types.isKeyword=function(a){return a instanceof F};function G(a){this.name=a;this.j=-1}G.prototype.toString=function(){return"[Symbol: "+this.name+"]"};
G.prototype.L=function(a){return C.a.equals(this,a)};G.prototype.equiv=G.prototype.L;G.prototype.G=function(a){return a instanceof G&&this.name==a.name};G.prototype.I=function(){-1===this.j&&(this.j=C.a.j(this.name));return this.j};C.types.symbol=function(a){return new G(a)};C.types.isSymbol=function(a){return a instanceof G};
C.types.ea=function(a,b,d){var e="";d=d||b+1;for(var f=8*(7-b),g=l(255).shiftLeft(f);b<d;b++,f-=8,g=ga(g,8)){var h=ga(u(a.A&g.A,a.p&g.p),f).toString(16);1==h.length&&(h="0"+h);e+=h}return e};function H(a,b){this.pa=a;this.ra=b;this.j=-1}H.prototype.toString=function(a){var b=this.pa,d=this.ra;a=""+(C.types.ea(b,0,4)+"-");a+=C.types.ea(b,4,6)+"-";a+=C.types.ea(b,6,8)+"-";a+=C.types.ea(d,0,2)+"-";return a+=C.types.ea(d,2,8)};H.prototype.L=function(a){return C.a.equals(this,a)};H.prototype.equiv=H.prototype.L;
H.prototype.G=function(a){return a instanceof H&&this.pa.equals(a.pa)&&this.ra.equals(a.ra)};H.prototype.I=function(){-1===this.j&&(this.j=C.a.j(this.toString()));return this.j};
C.types.UUIDfromString=function(a){a=a.replace(/-/g,"");for(var b=null,d=null,e=d=0,f=24,g=0,g=d=0,f=24;8>g;g+=2,f-=8)d|=parseInt(a.substring(g,g+2),16)<<f;e=0;g=8;for(f=24;16>g;g+=2,f-=8)e|=parseInt(a.substring(g,g+2),16)<<f;b=u(e,d);d=0;g=16;for(f=24;24>g;g+=2,f-=8)d|=parseInt(a.substring(g,g+2),16)<<f;e=0;for(f=g=24;32>g;g+=2,f-=8)e|=parseInt(a.substring(g,g+2),16)<<f;d=u(e,d);return new H(b,d)};C.types.uuid=function(a){return C.types.UUIDfromString(a)};
C.types.isUUID=function(a){return a instanceof H};C.types.date=function(a){a="number"===typeof a?a:parseInt(a,10);return new Date(a)};C.types.wb=function(a){return new Date(a)};Date.prototype.G=function(a){return a instanceof Date?this.valueOf()===a.valueOf():!1};Date.prototype.I=function(){return this.valueOf()};function ia(a,b){return b&&!1===b.ua||"undefined"==typeof Buffer?"undefined"!=typeof Uint8Array?C.g.Qa(a):C.types.K("b",a):new Buffer(a,"base64")}
C.types.isBinary=function(a){return"undefined"!=typeof Buffer&&a instanceof Buffer?!0:"undefined"!=typeof Uint8Array&&a instanceof Uint8Array?!0:a instanceof D&&"b"===a.tag};function ja(a){return C.types.K("r",a)}C.types.isURI=function(a){return a instanceof D&&"r"===a.tag};C.types.T=0;C.types.ga=1;C.types.za=2;function I(a,b){this.H=a;this.type=b||C.types.T;this.w=0}
I.prototype.next=function(){if(this.w<this.H.length){var a=null,a=this.type===C.types.T?this.H[this.w]:this.type===C.types.ga?this.H[this.w+1]:[this.H[this.w],this.H[this.w+1]],a={value:a,done:!1};this.w+=2;return a}return{value:null,done:!0}};I.prototype.next=I.prototype.next;function J(a,b){this.map=a;this.type=b||C.types.T;this.keys=ka(this.map);this.w=0;this.P=null;this.M=0}
J.prototype.next=function(){if(this.w<this.map.size){null!=this.P&&this.M<this.P.length||(this.P=this.map.map[this.keys[this.w]],this.M=0);var a=null,a=this.type===C.types.T?this.P[this.M]:this.type===C.types.ga?this.P[this.M+1]:[this.P[this.M],this.P[this.M+1]],a={value:a,done:!1};this.w++;this.M+=2;return a}return{value:null,done:!0}};J.prototype.next=J.prototype.next;
C.types.sa=function(a,b){if((b instanceof K||b instanceof L)&&a.size===b.size){for(var d in a.map)for(var e=a.map[d],f=0;f<e.length;f+=2)if(!C.a.equals(e[f+1],b.get(e[f])))return!1;return!0}if(null!=b&&"object"===typeof b&&(d=C.g.N(b),e=d.length,a.size===e)){for(f=0;f<e;f++){var g=d[f];if(!a.has(g)||!C.a.equals(b[g],a.get(g)))return!1}return!0}return!1};C.types.ka=8;C.types.ya=32;C.types.Pa=32;function L(a){this.v=a;this.o=null;this.j=-1;this.size=a.length/2;this.Ca=0}L.prototype.toString=function(){return"[TransitArrayMap]"};
function la(a){if(a.o)throw Error("Invalid operation, already converted");if(a.size<C.types.ka)return!1;a.Ca++;return a.Ca>C.types.Pa?(a.o=C.types.map(a.v,!1,!0),a.v=[],!0):!1}L.prototype.clear=function(){this.j=-1;this.o?this.o.clear():this.v=[];this.size=0};L.prototype.clear=L.prototype.clear;L.prototype.keys=function(){return this.o?this.o.keys():new I(this.v,C.types.T)};L.prototype.keys=L.prototype.keys;
L.prototype.Q=function(){if(this.o)return this.o.Q();for(var a=[],b=0,d=0;d<this.v.length;b++,d+=2)a[b]=this.v[d];return a};L.prototype.keySet=L.prototype.Q;L.prototype.H=function(){return this.o?this.o.H():new I(this.v,C.types.za)};L.prototype.entries=L.prototype.H;L.prototype.R=function(){return this.o?this.o.R():new I(this.v,C.types.ga)};L.prototype.values=L.prototype.R;L.prototype.forEach=function(a){if(this.o)this.o.forEach(a);else for(var b=0;b<this.v.length;b+=2)a(this.v[b+1],this.v[b])};
L.prototype.forEach=L.prototype.forEach;L.prototype.get=function(a,b){if(this.o)return this.o.get(a);if(la(this))return this.get(a);for(var d=0;d<this.v.length;d+=2)if(C.a.equals(this.v[d],a))return this.v[d+1];return b};L.prototype.get=L.prototype.get;L.prototype.has=function(a){if(this.o)return this.o.has(a);if(la(this))return this.has(a);for(var b=0;b<this.v.length;b+=2)if(C.a.equals(this.v[b],a))return!0;return!1};L.prototype.has=L.prototype.has;
L.prototype.set=function(a,b){this.j=-1;if(this.o)this.o.set(a,b),this.size=this.o.size;else{for(var d=0;d<this.v.length;d+=2)if(C.a.equals(this.v[d],a)){this.v[d+1]=b;return}this.v.push(a);this.v.push(b);this.size++;this.size>C.types.ya&&(this.o=C.types.map(this.v,!1,!0),this.v=null)}};L.prototype.set=L.prototype.set;
L.prototype["delete"]=function(a){this.j=-1;if(this.o)this.o["delete"](a),this.size=this.o.size;else for(var b=0;b<this.v.length;b+=2)if(C.a.equals(this.v[b],a)){this.v.splice(b,2);this.size--;break}};L.prototype.I=function(){if(this.o)return this.o.I();-1===this.j&&(this.j=C.a.hashMapLike(this));return this.j};L.prototype.G=function(a){return this.o?C.types.sa(this.o,a):C.types.sa(this,a)};function K(a,b,d){this.map=b||{};this.U=a||[];this.size=d||0;this.j=-1}K.prototype.toString=function(){return"[TransitMap]"};
K.prototype.clear=function(){this.j=-1;this.map={};this.U=[];this.size=0};K.prototype.clear=K.prototype.clear;function ka(a){return null!=a.U?a.U:C.g.N(a.map)}K.prototype["delete"]=function(a){this.j=-1;this.U=null;for(var b=C.a.j(a),d=this.map[b],e=0;e<d.length;e+=2)if(C.a.equals(a,d[e])){d.splice(e,2);0===d.length&&delete this.map[b];this.size--;break}};K.prototype.H=function(){return new J(this,C.types.za)};K.prototype.entries=K.prototype.H;
K.prototype.forEach=function(a){for(var b=ka(this),d=0;d<b.length;d++)for(var e=this.map[b[d]],f=0;f<e.length;f+=2)a(e[f+1],e[f],this)};K.prototype.forEach=K.prototype.forEach;K.prototype.get=function(a,b){var d=C.a.j(a),d=this.map[d];if(null!=d)for(var e=0;e<d.length;e+=2){if(C.a.equals(a,d[e]))return d[e+1]}else return b};K.prototype.get=K.prototype.get;K.prototype.has=function(a){var b=C.a.j(a),b=this.map[b];if(null!=b)for(var d=0;d<b.length;d+=2)if(C.a.equals(a,b[d]))return!0;return!1};
K.prototype.has=K.prototype.has;K.prototype.keys=function(){return new J(this,C.types.T)};K.prototype.keys=K.prototype.keys;K.prototype.Q=function(){for(var a=ka(this),b=[],d=0;d<a.length;d++)for(var e=this.map[a[d]],f=0;f<e.length;f+=2)b.push(e[f]);return b};K.prototype.keySet=K.prototype.Q;
K.prototype.set=function(a,b){this.j=-1;var d=C.a.j(a),e=this.map[d];if(null==e)this.U&&this.U.push(d),this.map[d]=[a,b],this.size++;else{for(var d=!0,f=0;f<e.length;f+=2)if(C.a.equals(b,e[f])){d=!1;e[f]=b;break}d&&(e.push(a),e.push(b),this.size++)}};K.prototype.set=K.prototype.set;K.prototype.R=function(){return new J(this,C.types.ga)};K.prototype.values=K.prototype.R;K.prototype.I=function(){-1===this.j&&(this.j=C.a.hashMapLike(this));return this.j};
K.prototype.G=function(a){return C.types.sa(this,a)};
C.types.map=function(a,b,d){a=a||[];b=!1===b?b:!0;if((!0!==d||!d)&&a.length<=2*C.types.ya){if(b){var e=a;a=[];for(b=0;b<e.length;b+=2){var f=!1;for(d=0;d<a.length;d+=2)if(C.a.equals(a[d],e[b])){a[d+1]=e[b+1];f=!0;break}f||(a.push(e[b]),a.push(e[b+1]))}}return new L(a)}var e={},f=[],g=0;for(b=0;b<a.length;b+=2){d=C.a.j(a[b]);var h=e[d];if(null==h)f.push(d),e[d]=[a[b],a[b+1]],g++;else{var k=!0;for(d=0;d<h.length;d+=2)if(C.a.equals(h[d],a[b])){h[d+1]=a[b+1];k=!1;break}k&&(h.push(a[b]),h.push(a[b+1]),
g++)}}return new K(f,e,g)};C.types.kb=function(a){return a instanceof L};C.types.isMap=function(a){return a instanceof L||a instanceof K};function M(a){this.map=a;this.size=a.size}M.prototype.toString=function(){return"[TransitSet]"};M.prototype.add=function(a){this.map.set(a,a);this.size=this.map.size};M.prototype.add=M.prototype.add;M.prototype.clear=function(){this.map=new K;this.size=0};M.prototype.clear=M.prototype.clear;M.prototype["delete"]=function(a){this.map["delete"](a);this.size=this.map.size};
M.prototype.H=function(){return this.map.H()};M.prototype.entries=M.prototype.H;M.prototype.forEach=function(a){var b=this;this.map.forEach(function(d,e){a(e,b)})};M.prototype.forEach=M.prototype.forEach;M.prototype.has=function(a){return this.map.has(a)};M.prototype.has=M.prototype.has;M.prototype.keys=function(){return this.map.keys()};M.prototype.keys=M.prototype.keys;M.prototype.Q=function(){return this.map.Q()};M.prototype.keySet=M.prototype.Q;M.prototype.R=function(){return this.map.R()};
M.prototype.values=M.prototype.R;M.prototype.G=function(a){if(a instanceof M){if(this.size===a.size)return C.a.equals(this.map,a.map)}else return!1};M.prototype.I=function(){return C.a.j(this.map)};C.types.set=function(a){a=a||[];for(var b={},d=[],e=0,f=0;f<a.length;f++){var g=C.a.j(a[f]),h=b[g];if(null==h)d.push(g),b[g]=[a[f],a[f]],e++;else{for(var g=!0,k=0;k<h.length;k+=2)if(C.a.equals(h[k],a[f])){g=!1;break}g&&(h.push(a[f]),h.push(a[f]),e++)}}return new M(new K(d,b,e))};
C.types.isSet=function(a){return a instanceof M};C.types.quoted=function(a){return C.types.K("'",a)};C.types.isQuoted=function(a){return a instanceof D&&"'"===a.tag};C.types.list=function(a){return C.types.K("list",a)};C.types.isList=function(a){return a instanceof C.types.xb&&"list"===a.tag};C.types.link=function(a){return C.types.K("link",a)};C.types.isLink=function(a){return a instanceof D&&"link"===a.tag};
C.types.tb=function(a){switch(a){case "-INF":return-Infinity;case "INF":return Infinity;case "NaN":return NaN;default:throw Error("Invalid special double value "+a);}};C.k={};C.k.Ua=3;C.k.X=48;C.k.Y=44;C.k.Aa=C.k.Y*C.k.Y;C.k.Ra=4096;C.k.Ka=function(a,b){if(a.length>C.k.Ua){if(b)return!0;var d=a.charAt(1);return a.charAt(0)===C.l.D?":"===d||"$"===d||"#"===d:!1}return!1};C.k.Ia=function(a){var b=Math.floor(a/C.k.Y);a=String.fromCharCode(a%C.k.Y+C.k.X);return 0===b?C.l.Z+a:C.l.Z+String.fromCharCode(b+C.k.X)+a};function N(){this.Za=this.ca=this.w=0;this.F={}}
N.prototype.write=function(a,b){if(C.k.Ka(a,b)){this.Za===C.k.Ra?(this.clear(),this.ca=0,this.F={}):this.w===C.k.Aa&&this.clear();var d=this.F[a];return null==d?(this.F[a]=[C.k.Ia(this.w),this.ca],this.w++,a):d[1]!=this.ca?(d[1]=this.ca,d[0]=C.k.Ia(this.w),this.w++,a):d[0]}return a};N.prototype.clear=function(){this.w=0;this.ca++};C.k.writeCache=function(){return new N};C.k.nb=function(a){return a.charAt(0)===C.l.Z&&" "!==a.charAt(1)};
C.k.ab=function(a){return 2===a.length?a.charCodeAt(1)-C.k.X:(a.charCodeAt(1)-C.k.X)*C.k.Y+(a.charCodeAt(2)-C.k.X)};function O(){this.w=0;this.F=[]}O.prototype.write=function(a){this.w==C.k.Aa&&(this.w=0);this.F[this.w]=a;this.w++;return a};O.prototype.va=function(a){return this.F[C.k.ab(a)]};O.prototype.clear=function(){this.w=0};C.k.readCache=function(){return new O};C.e={};C.e.decoder={};function na(a){this.ia=a}C.e.decoder.tag=function(a){return new na(a)};C.e.decoder.La=function(a){return a&&a instanceof na};C.e.decoder.pb=function(a){switch(a){case "_":case "s":case "?":case "i":case "d":case "b":case "'":case "array":case "map":return!0}return!1};
function P(a){this.options=a||{};this.h={};for(var b in this.ba.h)this.h[b]=this.ba.h[b];for(b in this.options.handlers){if(C.e.decoder.pb(b))throw Error('Cannot override handler for ground type "'+b+'"');this.h[b]=this.options.handlers[b]}this.ha=null!=this.options.preferStrings?this.options.preferStrings:this.ba.ha;this.ua=null!=this.options.preferBuffers?this.options.preferBuffers:this.ba.ua;this.ma=this.options.defaultHandler||this.ba.ma;this.J=this.options.mapBuilder;this.V=this.options.arrayBuilder}
P.prototype.ba={h:{_:function(){return null},"?":function(a){return C.types.Ya(a)},b:function(a,b){return ia(a,b)},i:function(a){return C.types.Ja(a)},n:function(a){return C.types.Da(a)},d:function(a){return C.types.ib(a)},f:function(a){return ha(a)},c:function(a){return C.types.$a(a)},":":function(a){return C.types.keyword(a)},$:function(a){return C.types.symbol(a)},r:function(a){return ja(a)},z:function(a){return C.types.tb(a)},"'":function(a){return a},m:function(a){return C.types.date(a)},t:function(a){return C.types.wb(a)},
u:function(a){return C.types.uuid(a)},set:function(a){return C.types.set(a)},list:function(a){return C.types.list(a)},link:function(a){return C.types.link(a)},cmap:function(a){return C.types.map(a,!1)}},ma:function(a,b){return C.types.K(a,b)},ha:!0,ua:!0};
P.prototype.B=function(a,b,d,e){if(null==a)return null;switch(typeof a){case "string":return C.k.Ka(a,d)?(a=oa(this,a),b&&b.write(a,d),b=a):b=C.k.nb(a)?b.va(a,d):oa(this,a),b;case "object":if(C.g.isArray(a))if("^ "===a[0])if(this.J)if(a.length<2*C.types.ka+1&&this.J.fromArray){e=[];for(d=1;d<a.length;d+=2)e.push(this.B(a[d],b,!0,!1)),e.push(this.B(a[d+1],b,!1,!1));b=this.J.fromArray(e,a)}else{e=this.J.init(a);for(d=1;d<a.length;d+=2)e=this.J.add(e,this.B(a[d],b,!0,!1),this.B(a[d+1],b,!1,!1),a);b=
this.J.finalize(e,a)}else{e=[];for(d=1;d<a.length;d+=2)e.push(this.B(a[d],b,!0,!1)),e.push(this.B(a[d+1],b,!1,!1));b=C.types.map(e,!1)}else b=pa(this,a,b,d,e);else{d=C.g.N(a);var f=d[0];e=1==d.length?this.B(f,b,!1,!1):null;if(C.e.decoder.La(e))a=a[f],d=this.h[e.ia],b=null!=d?d(this.B(a,b,!1,!0),this):C.types.K(e.ia,this.B(a,b,!1,!1));else if(this.J)if(d.length<2*C.types.ka&&this.J.fromArray){var g=[];for(e=0;e<d.length;e++)f=d[e],g.push(this.B(f,b,!0,!1)),g.push(this.B(a[f],b,!1,!1));b=this.J.fromArray(g,
a)}else{g=this.J.init(a);for(e=0;e<d.length;e++)f=d[e],g=this.J.add(g,this.B(f,b,!0,!1),this.B(a[f],b,!1,!1),a);b=this.J.finalize(g,a)}else{g=[];for(e=0;e<d.length;e++)f=d[e],g.push(this.B(f,b,!0,!1)),g.push(this.B(a[f],b,!1,!1));b=C.types.map(g,!1)}}return b}return a};P.prototype.decode=P.prototype.B;
function pa(a,b,d,e,f){if(f){var g=[];for(f=0;f<b.length;f++)g.push(a.B(b[f],d,e,!1));return g}g=d&&d.w;if(2===b.length&&"string"===typeof b[0]&&(f=a.B(b[0],d,!1,!1),C.e.decoder.La(f)))return b=b[1],g=a.h[f.ia],null!=g?g=g(a.B(b,d,e,!0),a):C.types.K(f.ia,a.B(b,d,e,!1));d&&g!=d.w&&(d.w=g);if(a.V){if(32>=b.length&&a.V.fromArray){g=[];for(f=0;f<b.length;f++)g.push(a.B(b[f],d,e,!1));return a.V.fromArray(g,b)}g=a.V.init();for(f=0;f<b.length;f++)g=a.V.add(g,a.B(b[f],d,e,!1),b);return a.V.finalize(g,b)}g=
[];for(f=0;f<b.length;f++)g.push(a.B(b[f],d,e,!1));return g}function oa(a,b){if(b.charAt(0)===C.l.D){var d=b.charAt(1);if(d===C.l.D||d===C.l.Z||d===C.l.Ba)return b.substring(1);if(d===C.l.Wa)return C.e.decoder.tag(b.substring(2));var e=a.h[d];return null==e?a.ma(d,b.substring(2)):e(b.substring(2),a)}return b}C.e.decoder.decoder=function(a){return new P(a)};C.e.reader={};function qa(a){this.decoder=new P(a)}function Q(a,b){this.ub=a;this.options=b||{};this.F=this.options.cache?this.options.cache:new O}Q.prototype.va=function(a){var b=this.F;a=this.ub.decoder.B(JSON.parse(a),b);this.F.clear();return a};Q.prototype.read=Q.prototype.va;C.h={};C.h.Fa=0;C.h.la="transit$guid$"+C.g.randomUUID();C.h.Oa=function(a){if(null==a)return"null";if(a===String)return"string";if(a===Boolean)return"boolean";if(a===Number)return"number";if(a===Array)return"array";if(a===Object)return"map";var b=a[C.h.la];null==b&&("undefined"!=typeof Object.defineProperty?(b=++C.h.Fa,Object.defineProperty(a,C.h.la,{value:b,enumerable:!1})):a[C.h.la]=b=++C.h.Fa);return b};C.h.constructor=function(a){return null==a?null:a.constructor};
C.h.W=function(a,b){for(var d=a.toString(),e=d.length;e<b;e++)d="0"+d;return d};C.h.stringableKeys=function(a){a=C.g.N(a);for(var b=0;b<a.length;b++);return!0};function R(){}R.prototype.tag=function(){return"_"};R.prototype.rep=function(){return null};R.prototype.C=function(){return"null"};function S(){}S.prototype.tag=function(){return"s"};S.prototype.rep=function(a){return a};S.prototype.C=function(a){return a};function T(){}T.prototype.tag=function(){return"i"};T.prototype.rep=function(a){return a};
T.prototype.C=function(a){return a.toString()};function U(){}U.prototype.tag=function(){return"i"};U.prototype.rep=function(a){return a.toString()};U.prototype.C=function(a){return a.toString()};function V(){}V.prototype.tag=function(){return"?"};V.prototype.rep=function(a){return a};V.prototype.C=function(a){return a.toString()};function ra(){}ra.prototype.tag=function(){return"array"};ra.prototype.rep=function(a){return a};ra.prototype.C=function(){return null};function sa(){}sa.prototype.tag=function(){return"map"};
sa.prototype.rep=function(a){return a};sa.prototype.C=function(){return null};function ta(){}ta.prototype.tag=function(){return"t"};ta.prototype.rep=function(a){return a.getUTCFullYear()+"-"+C.h.W(a.getUTCMonth()+1,2)+"-"+C.h.W(a.getUTCDate(),2)+"T"+C.h.W(a.getUTCHours(),2)+":"+C.h.W(a.getUTCMinutes(),2)+":"+C.h.W(a.getUTCSeconds(),2)+"."+C.h.W(a.getUTCMilliseconds(),3)+"Z"};ta.prototype.C=function(a,b){return b.rep(a)};function W(){}W.prototype.tag=function(){return"m"};W.prototype.rep=function(a){return a.valueOf()};
W.prototype.C=function(a){return a.valueOf().toString()};W.prototype.Ga=function(){return new ta};function ua(){}ua.prototype.tag=function(){return"u"};ua.prototype.rep=function(a){return a.toString()};ua.prototype.C=function(a){return a.toString()};function va(){}va.prototype.tag=function(){return":"};va.prototype.rep=function(a){return a.name};va.prototype.C=function(a,b){return b.rep(a)};function wa(){}wa.prototype.tag=function(){return"$"};wa.prototype.rep=function(a){return a.name};
wa.prototype.C=function(a,b){return b.rep(a)};function xa(){}xa.prototype.tag=function(a){return a.tag};xa.prototype.rep=function(a){return a.rep};xa.prototype.C=function(){return null};function ya(){}ya.prototype.tag=function(){return"set"};ya.prototype.rep=function(a){var b=[];a.forEach(function(a){b.push(a)});return C.types.K("array",b)};ya.prototype.C=function(){return null};function za(){}za.prototype.tag=function(){return"map"};za.prototype.rep=function(a){return a};za.prototype.C=function(){return null};
function Aa(){}Aa.prototype.tag=function(){return"map"};Aa.prototype.rep=function(a){return a};Aa.prototype.C=function(){return null};function Ba(){}Ba.prototype.tag=function(){return"b"};Ba.prototype.rep=function(a){return a.toString("base64")};Ba.prototype.C=function(){return null};function Ca(){}Ca.prototype.tag=function(){return"b"};Ca.prototype.rep=function(a){return C.g.Xa(a)};Ca.prototype.C=function(){return null};
C.h.bb=function(a){a.set(null,new R);a.set(String,new S);a.set(Number,new T);a.set(c,new U);a.set(Boolean,new V);a.set(Array,new ra);a.set(Object,new sa);a.set(Date,new W);a.set(H,new ua);a.set(F,new va);a.set(G,new wa);a.set(D,new xa);a.set(M,new ya);a.set(L,new za);a.set(K,new Aa);"undefined"!=typeof Buffer&&a.set(Buffer,new Ba);"undefined"!=typeof Uint8Array&&a.set(Uint8Array,new Ca)};function X(){this.h={};C.h.bb(this)}
X.prototype.get=function(a){var b=null,b="string"===typeof a?this.h[a]:this.h[C.h.Oa(a)];return null!=b?b:this.h["default"]};X.prototype.get=X.prototype.get;C.h.vb=function(a){switch(a){case "null":case "string":case "boolean":case "number":case "array":case "map":return!1}return!0};X.prototype.set=function(a,b){"string"===typeof a&&C.h.vb(a)?this.h[a]=b:this.h[C.h.Oa(a)]=b};C.e.writer={};C.e.writer.escape=function(a){if(0<a.length){var b=a.charAt(0);return b===C.l.D||b===C.l.Z||b===C.l.Ba?C.l.D+a:a}return a};
function Da(a){this.O=a||{};this.ha=null!=this.O.preferStrings?this.O.preferStrings:!0;this.Ma=this.O.objectBuilder||null;this.h=new X;if(a=this.O.handlers){if(C.g.isArray(a)||!a.forEach)throw Error('transit writer "handlers" option must be a map');var b=this;a.forEach(function(a,e){b.h.set(e,a)})}this.da=this.O.handlerForForeign;this.ja=this.O.unpack||function(a){return C.types.kb(a)&&null===a.o?a.v:!1};this.fa=this.O&&this.O.verbose||!1}
function Ea(a,b){var d=a.h.get(C.h.constructor(b));return null!=d?d:(d=b&&b.transitTag)?a.h.get(d):null}function Y(a,b,d,e,f){a=a+b+d;return f?f.write(a,e):a}C.e.writer.gb=function(a,b,d){var e=[];if(C.g.isArray(b))for(var f=0;f<b.length;f++)e.push(C.e.writer.s(a,b[f],!1,d));else b.forEach(function(b){e.push(C.e.writer.s(a,b,!1,d))});return e};C.e.writer.cb=function(a,b,d){return C.e.writer.gb(a,b,d)};C.e.writer.qa=function(a,b){if("string"!==typeof b){var d=Ea(a,b);return d&&1===d.tag(b).length}return!0};
C.e.writer.stringableKeys=function(a,b){var d=a.ja(b),e=!0;if(d){for(var f=0;f<d.length&&(e=C.e.writer.qa(a,d[f]),e);f+=2);return e}if(b.keys&&(d=b.keys(),f=null,d.next)){for(f=d.next();!f.done;){e=C.e.writer.qa(a,f.value);if(!e)break;f=d.next()}return e}if(b.forEach)return b.forEach(function(b,d){e=e&&C.e.writer.qa(a,d)}),e;throw Error("Cannot walk keys of object type "+C.h.constructor(b).name);};
C.e.writer.ob=function(a){if(a.constructor.transit$isObject)return!0;var b=a.constructor.toString(),b=b.substr(9),b=b.substr(0,b.indexOf("(")),b="Object"==b;"undefined"!=typeof Object.defineProperty?Object.defineProperty(a.constructor,"transit$isObject",{value:b,enumerable:!1}):a.constructor.transit$isObject=b;return b};
C.e.writer.fb=function(a,b,d){if(b.constructor===Object||null!=b.forEach||a.da&&C.e.writer.ob(b)){if(a.fa){if(null!=b.forEach)if(C.e.writer.stringableKeys(a,b)){var e={};b.forEach(function(b,f){e[C.e.writer.s(a,f,!0,!1)]=C.e.writer.s(a,b,!1,d)})}else{var f=a.ja(b),g=[],h=Y(C.l.S,"cmap","",!0,d);if(f)for(var k=0;k<f.length;k+=2)g.push(C.e.writer.s(a,f[k],!0,!1)),g.push(C.e.writer.s(a,f[k+1],!1,d));else b.forEach(function(b,e){g.push(C.e.writer.s(a,e,!0,!1));g.push(C.e.writer.s(a,b,!1,d))});e={};e[h]=
g}else for(e={},f=C.g.N(b),k=0;k<f.length;k++)e[C.e.writer.s(a,f[k],!0,!1)]=C.e.writer.s(a,b[f[k]],!1,d);return e}if(null!=b.forEach){if(C.e.writer.stringableKeys(a,b)){f=a.ja(b);e=["^ "];if(f)for(k=0;k<f.length;k+=2)e.push(C.e.writer.s(a,f[k],!0,d)),e.push(C.e.writer.s(a,f[k+1],!1,d));else b.forEach(function(b,f){e.push(C.e.writer.s(a,f,!0,d));e.push(C.e.writer.s(a,b,!1,d))});return e}f=a.ja(b);g=[];h=Y(C.l.S,"cmap","",!0,d);if(f)for(k=0;k<f.length;k+=2)g.push(C.e.writer.s(a,f[k],!0,d)),g.push(C.e.writer.s(a,
f[k+1],!1,d));else b.forEach(function(b,e){g.push(C.e.writer.s(a,e,!0,d));g.push(C.e.writer.s(a,b,!1,d))});return[h,g]}e=["^ "];f=C.g.N(b);for(k=0;k<f.length;k++)e.push(C.e.writer.s(a,f[k],!0,d)),e.push(C.e.writer.s(a,b[f[k]],!1,d));return e}if(null!=a.Ma)return a.Ma(b,function(b){return C.e.writer.s(a,b,!0,d)},function(b){return C.e.writer.s(a,b,!1,d)});k=C.h.constructor(b).name;f=Error("Cannot write "+k);f.data={ta:b,type:k};throw f;};
C.e.writer.hb=function(a,b,d,e){if(a.fa){var f={};f[Y(C.l.S,b,"",!0,e)]=C.e.writer.s(a,d,!1,e);return f}return[Y(C.l.S,b,"",!0,e),C.e.writer.s(a,d,!1,e)]};C.e.writer.eb=function(a,b,d,e,f,g,h){if(1===d.length){if("string"===typeof e)return Y(C.l.D,d,e,g,h);if(g||a.ha){(e=a.fa&&b.Ga())?(d=e.tag(f),e=e.C(f,e)):e=b.C(f,b);if(null!==e)return Y(C.l.D,d,e,g,h);b=Error('Tag "'+d+'" cannot be encoded as string');b.data={tag:d,rep:e,ta:f};throw b;}}return C.e.writer.hb(a,d,e,h)};
C.e.writer.s=function(a,b,d,e){var f=Ea(a,b)||(a.da?a.da(b,a.h):null),g=f?f.tag(b):null,h=f?f.rep(b):null;if(null!=f&&null!=g)switch(g){case "_":return d?Y(C.l.D,"_","",d,e):null;case "s":return Y("","",C.e.writer.escape(h),d,e);case "?":return d?Y(C.l.D,"?",h.toString()[0],d,e):h;case "i":return Infinity===h?Y(C.l.D,"z","INF",d,e):-Infinity===h?Y(C.l.D,"z","-INF",d,e):isNaN(h)?Y(C.l.D,"z","NaN",d,e):d||"string"===typeof h||h instanceof c?Y(C.l.D,"i",h.toString(),d,e):h;case "d":return d?Y(h.D,"d",
h,d,e):h;case "b":return Y(C.l.D,"b",h,d,e);case "'":return a.fa?(b={},d=Y(C.l.S,"'","",!0,e),b[d]=C.e.writer.s(a,h,!1,e),a=b):a=[Y(C.l.S,"'","",!0,e),C.e.writer.s(a,h,!1,e)],a;case "array":return C.e.writer.cb(a,h,e);case "map":return C.e.writer.fb(a,h,e);default:return C.e.writer.eb(a,f,g,h,b,d,e)}else throw a=C.h.constructor(b).name,e=Error("Cannot write "+a),e.data={ta:b,type:a},e;};
C.e.writer.sb=function(a,b){var d=Ea(a,b)||(a.da?a.da(b,a.h):null);if(null!=d)return 1===d.tag(b).length?C.types.quoted(b):b;var d=C.h.constructor(b).name,e=Error("Cannot write "+d);e.data={ta:b,type:d};throw e;};C.e.writer.qb=function(a,b,d,e){return JSON.stringify(C.e.writer.s(a,C.e.writer.sb(a,b),d,e))};function Z(a,b){this.aa=a;this.options=b||{};this.F=!1===this.options.cache?null:this.options.cache?this.options.cache:new N}Z.prototype.rb=function(){return this.aa};Z.prototype.marshaller=Z.prototype.rb;
Z.prototype.write=function(a,b){var d=null,d=b||{},e=d.asMapKey||!1,f=this.aa.fa?!1:this.F,d=!1===d.marshalTop?C.e.writer.s(this.aa,a,e,f):C.e.writer.qb(this.aa,a,e,f);null!=this.F&&this.F.clear();return d};Z.prototype.write=Z.prototype.write;Z.prototype.register=function(a,b){this.aa.h.set(a,b)};Z.prototype.register=Z.prototype.register;C.reader=function(a,b){if("json"===a||"json-verbose"===a||null==a){var d=new qa(b);return new Q(d,b)}throw Error("Cannot create reader of type "+a);};C.writer=function(a,b){if("json"===a||"json-verbose"===a||null==a){"json-verbose"===a&&(null==b&&(b={}),b.verbose=!0);var d=new Da(b);return new Z(d,b)}d=Error('Type must be "json"');d.data={type:a};throw d;};
C.makeWriteHandler=function(a){function b(){}b.prototype.tag=a.tag;b.prototype.rep=a.rep;b.prototype.C=a.stringRep;b.prototype.Ga=a.getVerboseHandler;return new b};C.makeBuilder=function(a){function b(){}b.prototype.init=a.init;b.prototype.add=a.add;b.prototype.finalize=a.finalize;b.prototype.fromArray=a.fromArray;return new b};C.date=C.types.date;C.integer=C.types.Ja;C.isInteger=C.types.isInteger;C.uuid=C.types.uuid;C.isUUID=C.types.isUUID;C.bigInt=C.types.Da;C.isBigInt=C.types.mb;C.bigDec=ha;
C.isBigDec=C.types.lb;C.keyword=C.types.keyword;C.isKeyword=C.types.isKeyword;C.symbol=C.types.symbol;C.isSymbol=C.types.isSymbol;C.binary=ia;C.isBinary=C.types.isBinary;C.uri=ja;C.isURI=C.types.isURI;C.map=C.types.map;C.isMap=C.types.isMap;C.set=C.types.set;C.isSet=C.types.isSet;C.list=C.types.list;C.isList=C.types.isList;C.quoted=C.types.quoted;C.isQuoted=C.types.isQuoted;C.tagged=C.types.K;C.isTaggedValue=C.types.isTaggedValue;C.link=C.types.link;C.isLink=C.types.isLink;C.hash=C.a.j;
C.hashMapLike=C.a.hashMapLike;C.hashMapLike=C.a.hashArrayLike;C.equals=C.a.equals;C.extendToEQ=C.a.extendToEQ;C.mapToObject=function(a){var b={};a.forEach(function(a,e){if("string"!==typeof e)throw Error("Cannot convert map with non-string keys");b[e]=a});return b};C.decoder=C.e.decoder.decoder;C.readCache=C.k.readCache;C.writeCache=C.k.writeCache;C.UUIDfromString=C.types.UUIDfromString;C.randomUUID=C.types.randomUUID;C.stringableKeys=C.e.writer.stringableKeys;define("transit",[],function(){return C});})();
