// transit-js 0.8.867
// http://transit-format.org
// 
// Copyright 2014 Cognitect. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License..
;(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function aa(b){var c=0;return function(){return c<b.length?{done:!1,value:b[c++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,d){if(b==Array.prototype||b==Object.prototype)return b;b[c]=d.value;return b};
function ca(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");}var da=ca(this);function k(b,c){if(c)a:{var d=da;b=b.split(".");for(var e=0;e<b.length-1;e++){var f=b[e];if(!(f in d))break a;d=d[f]}b=b[b.length-1];e=d[b];c=c(e);c!=e&&null!=c&&ba(d,b,{configurable:!0,writable:!0,value:c})}}
k("Symbol",function(b){function c(f){if(this instanceof c)throw new TypeError("Symbol is not a constructor");return new d("jscomp_symbol_"+(f||"")+"_"+e++,f)}function d(f,g){this.a=f;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(b)return b;d.prototype.toString=function(){return this.a};var e=0;return c});
k("Symbol.iterator",function(b){if(b)return b;b=Symbol("Symbol.iterator");for(var c="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<c.length;d++){var e=da[c[d]];"function"===typeof e&&"function"!=typeof e.prototype[b]&&ba(e.prototype,b,{configurable:!0,writable:!0,value:function(){return ea(aa(this))}})}return b});function ea(b){b={next:b};b[Symbol.iterator]=function(){return this};return b}
function fa(b,c){b instanceof String&&(b+="");var d=0,e={next:function(){if(d<b.length){var f=d++;return{value:c(f,b[f]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e}k("Array.prototype.entries",function(b){return b?b:function(){return fa(this,function(c,d){return[c,d]})}});k("Array.prototype.keys",function(b){return b?b:function(){return fa(this,function(c){return c})}});
k("Array.prototype.values",function(b){return b?b:function(){return fa(this,function(c,d){return d})}});var ha=ha||{},l=this||self;function m(b,c){b=b.split(".");var d=l;b[0]in d||"undefined"==typeof d.execScript||d.execScript("var "+b[0]);for(var e;b.length&&(e=b.shift());)b.length||void 0===c?d[e]&&d[e]!==Object.prototype[e]?d=d[e]:d=d[e]={}:d[e]=c};var n="undefined"!=typeof Object.keys?function(b){return Object.keys(b)}:function(b){var c=[],d=0,e;for(e in b)c[d++]=e;return c},q="undefined"!=typeof Array.isArray?function(b){return Array.isArray(b)}:function(b){var c=typeof b;return"array"===("object"!=c?c:b?Array.isArray(b)?"array":c:"null")};function r(){return Math.round(15*Math.random()).toString(16)}
function ja(){var b=(8|3&Math.round(14*Math.random())).toString(16);return r()+r()+r()+r()+r()+r()+r()+r()+"-"+r()+r()+r()+r()+"-4"+r()+r()+r()+"-"+b+r()+r()+r()+"-"+r()+r()+r()+r()+r()+r()+r()+r()+r()+r()+r()+r()};function ka(b,c){if(3<b.length){if(c)return!0;c=b.charAt(1);return"~"===b.charAt(0)?":"===c||"$"===c||"#"===c:!1}return!1}function la(b){var c=Math.floor(b/44);b=String.fromCharCode(b%44+48);return 0===c?"^"+b:"^"+String.fromCharCode(c+48)+b}function ma(){this.a=this.l=0;this.cache={}}ma.prototype.write=function(b,c){return ka(b,c)?(1936===this.l&&this.clear(),c=this.cache[b],null==c?(this.cache[b]=[la(this.l),this.a],this.l++,b):c[1]!=this.a?(c[1]=this.a,c[0]=la(this.l),this.l++,b):c[0]):b};
ma.prototype.clear=function(){this.l=0;this.a++};function t(){this.l=0;this.cache=[]}t.prototype.write=function(b){1936==this.l&&(this.l=0);this.cache[this.l]=b;this.l++;return b};t.prototype.read=function(b){return this.cache[2===b.length?b.charCodeAt(1)-48:44*(b.charCodeAt(1)-48)+(b.charCodeAt(2)-48)]};t.prototype.clear=function(){this.l=0};var na=1;function u(b,c){if(null==b)return null==c;if(b===c)return!0;if("object"===typeof b){if(q(b)){if(q(c)&&b.length===c.length){for(var d=0;d<b.length;d++)if(!u(b[d],c[d]))return!1;return!0}return!1}if(b.B)return b.B(c);if(null!=c&&"object"===typeof c){if(c.B)return c.B(b);d=0;var e=n(c).length,f;for(f in b)if(b.hasOwnProperty(f)&&(d++,!c.hasOwnProperty(f)||!u(b[f],c[f])))return!1;return d===e}}return!1}function oa(b,c){return b^c+2654435769+(b<<6)+(b>>2)}var pa={},qa=0;
function ra(b){var c=0;if(null!=b.forEach)b.forEach(function(h,p){c=(c+(v(p)^v(h)))%4503599627370496});else for(var d=n(b),e=0;e<d.length;e++){var f=d[e],g=b[f];c=(c+(v(f)^v(g)))%4503599627370496}return c}function sa(b){var c=0;if(q(b))for(var d=0;d<b.length;d++)c=oa(c,v(b[d]));else b.forEach&&b.forEach(function(e){c=oa(c,v(e))});return c}
function v(b){if(null==b)return 0;switch(typeof b){case "number":return b;case "boolean":return!0===b?1:0;case "string":var c=pa[b];if(null!=c)b=c;else{for(var d=c=0;d<b.length;++d)c=31*c+b.charCodeAt(d),c%=4294967296;qa++;256<=qa&&(pa={},qa=1);b=pa[b]=c}return b;case "function":if(c=b.transit$hashCode$)return c;c=na;"undefined"!=typeof Object.defineProperty?Object.defineProperty(b,"transit$hashCode$",{value:c,enumerable:!1}):b.transit$hashCode$=c;na++;return c;default:return b instanceof Date?b.valueOf():
q(b)?sa(b):b.C?b.C():ra(b)}};function w(b,c){this.g=b|0;this.a=c|0}function x(b){return 4294967296*b.a+(b.g>>>0)}
w.prototype.toString=function(b){b=b||10;if(2>b||36<b)throw Error("radix out of range: "+b);var c=this.a>>21;if(0==c||-1==c&&(0!=this.g||-2097152!=this.a))return c=x(this),10==b?""+c:c.toString(b);c=14-(b>>2);var d=Math.pow(b,c),e=y(d,d/4294967296);d=B(this,e);e=Math.abs(x(this.add(C(D(d,e)))));var f=10==b?""+e:e.toString(b);f.length<c&&(f="0000000000000".substr(f.length-c)+f);e=x(d);return(10==b?e:e.toString(b))+f};function E(b){return 0==b.g&&0==b.a}function G(b,c){return b.g==c.g&&b.a==c.a}
function ta(b,c){return b.a==c.a?b.g==c.g?0:b.g>>>0>c.g>>>0?1:-1:b.a>c.a?1:-1}function C(b){var c=~b.g+1|0;return y(c,~b.a+!c|0)}w.prototype.add=function(b){var c=this.a>>>16,d=this.a&65535,e=this.g>>>16,f=b.a>>>16,g=b.a&65535,h=b.g>>>16;b=(this.g&65535)+(b.g&65535);h=(b>>>16)+(e+h);e=h>>>16;e+=d+g;c=(e>>>16)+(c+f)&65535;return y((h&65535)<<16|b&65535,c<<16|e&65535)};
function D(b,c){if(E(b))return b;if(E(c))return c;var d=b.a>>>16,e=b.a&65535,f=b.g>>>16;b=b.g&65535;var g=c.a>>>16,h=c.a&65535,p=c.g>>>16;c=c.g&65535;var z=b*c;var A=(z>>>16)+f*c;var F=A>>>16;A=(A&65535)+b*p;F+=A>>>16;F+=e*c;var ia=F>>>16;F=(F&65535)+f*p;ia+=F>>>16;F=(F&65535)+b*h;ia=ia+(F>>>16)+(d*c+e*p+f*h+b*g)&65535;return y((A&65535)<<16|z&65535,ia<<16|F&65535)}
function B(b,c){if(E(c))throw Error("division by zero");if(0>b.a){if(G(b,H)){if(G(c,ua)||G(c,va))return H;if(G(c,H))return ua;var d=1;if(0==d)d=b;else{var e=b.a;d=32>d?y(b.g>>>d|e<<32-d,e>>d):y(e>>d-32,0<=e?0:-1)}d=wa(B(d,c),1);if(G(d,I))return 0>c.a?ua:va;b=b.add(C(D(c,d)));return d.add(B(b,c))}return 0>c.a?B(C(b),C(c)):C(B(C(b),c))}if(E(b))return I;if(0>c.a)return G(c,H)?I:C(B(b,C(c)));for(e=I;0<=ta(b,c);){d=Math.max(1,Math.floor(x(b)/x(c)));var f=Math.ceil(Math.log(d)/Math.LN2);f=48>=f?1:Math.pow(2,
f-48);for(var g=J(d),h=D(g,c);0>h.a||0<ta(h,b);)d-=f,g=J(d),h=D(g,c);E(g)&&(g=ua);e=e.add(g);b=b.add(C(h))}return e}w.prototype.and=function(b){return y(this.g&b.g,this.a&b.a)};w.prototype.or=function(b){return y(this.g|b.g,this.a|b.a)};w.prototype.xor=function(b){return y(this.g^b.g,this.a^b.a)};function wa(b,c){c&=63;if(0==c)return b;var d=b.g;return 32>c?y(d<<c,b.a<<c|d>>>32-c):y(0,d<<c-32)}
function xa(b,c){c&=63;if(0==c)return b;var d=b.a;return 32>c?y(b.g>>>c|d<<32-c,d>>>c):32==c?y(d,0):y(d>>>c-32,0)}function J(b){return 0<b?0x7fffffffffffffff<=b?ya:new w(b,b/4294967296):0>b?-9223372036854775808>=b?H:C(new w(-b,-b/4294967296)):I}function y(b,c){return new w(b,c)}
function za(b,c){if("-"==b.charAt(0))return C(za(b.substring(1),c));var d=parseInt(b,c||10);if(9007199254740991>=d)return new w(d%4294967296|0,d/4294967296|0);if(0==b.length)throw Error("number format error: empty string");if(0<=b.indexOf("-"))throw Error('number format error: interior "-" character: '+b);c=c||10;if(2>c||36<c)throw Error("radix out of range: "+c);d=J(Math.pow(c,8));for(var e=I,f=0;f<b.length;f+=8){var g=Math.min(8,b.length-f),h=parseInt(b.substring(f,f+g),c);8>g?e=D(e,J(Math.pow(c,
g))).add(J(h)):(e=D(e,d),e=e.add(J(h)))}return e}var I=y(0,0),ua=y(1,0),va=y(-1,-1),ya=y(4294967295,2147483647),H=y(0,2147483648);var Aa="undefined"!=typeof Symbol?Symbol.iterator:"@@iterator";function K(b,c){this.tag=b;this.rep=c;this.a=-1}K.prototype.toString=function(){return"[TaggedValue: "+this.tag+", "+this.rep+"]"};K.prototype.g=function(b){return u(this,b)};K.prototype.equiv=K.prototype.g;K.prototype.B=function(b){return b instanceof K?this.tag===b.tag&&u(this.rep,b.rep):!1};K.prototype.C=function(){-1===this.a&&(this.a=oa(v(this.tag),v(this.rep)));return this.a};function L(b,c){return new K(b,c)}
var Ba=za("9007199254740991"),Ca=za("-9007199254740991");function Da(b){if("number"===typeof b)return b;if(b instanceof w)return b;b=za(b,10);var c;(c=0<ta(b,Ba))||(c=0>ta(b,Ca));return c?b:x(b)}w.prototype.s=function(b){return u(this,b)};w.prototype.equiv=w.prototype.s;w.prototype.B=function(b){return b instanceof w&&G(this,b)};w.prototype.C=function(){return this.g};function Ea(b){return L("n",b)}function Fa(b){return L("f",b)}function M(b){this.o=b;this.a=-1}
M.prototype.toString=function(){return":"+this.o};M.prototype.namespace=function(){var b=this.o.indexOf("/");return-1!=b?this.o.substring(0,b):null};M.prototype.name=function(){var b=this.o.indexOf("/");return-1!=b?this.o.substring(b+1,this.o.length):this.o};M.prototype.g=function(b){return u(this,b)};M.prototype.equiv=M.prototype.g;M.prototype.B=function(b){return b instanceof M&&this.o==b.o};M.prototype.C=function(){-1===this.a&&(this.a=v(this.o));return this.a};function Ga(b){return new M(b)}
function N(b){this.o=b;this.a=-1}N.prototype.namespace=function(){var b=this.o.indexOf("/");return-1!=b?this.o.substring(0,b):null};N.prototype.name=function(){var b=this.o.indexOf("/");return-1!=b?this.o.substring(b+1,this.o.length):this.o};N.prototype.toString=function(){return this.o};N.prototype.g=function(b){return u(this,b)};N.prototype.equiv=N.prototype.g;N.prototype.B=function(b){return b instanceof N&&this.o==b.o};N.prototype.C=function(){-1===this.a&&(this.a=v(this.o));return this.a};
function Ha(b){return new N(b)}function Ia(b,c,d){var e="";d=d||c+1;for(var f=8*(7-c),g=wa(new w(255,0),f);c<d;c++,f-=8,g=xa(g,8)){var h=xa(b.and(g),f).toString(16);1==h.length&&(h="0"+h);e+=h}return e}function O(b,c){this.g=b;this.s=c;this.a=-1}O.prototype.toString=function(){var b=this.g,c=this.s;var d=Ia(b,0,4)+"-";d+=Ia(b,4,6)+"-";d+=Ia(b,6,8)+"-";d+=Ia(c,0,2)+"-";return d+=Ia(c,2,8)};O.prototype.D=function(b){return u(this,b)};O.prototype.equiv=O.prototype.D;
O.prototype.B=function(b){return b instanceof O&&G(this.g,b.g)&&G(this.s,b.s)};O.prototype.C=function(){-1===this.a&&(this.a=v(this.toString()));return this.a};
function Ja(b){b=b.replace(/-/g,"");var c,d;var e=c=0;for(d=24;8>e;e+=2,d-=8)c|=parseInt(b.substring(e,e+2),16)<<d;var f=0;e=8;for(d=24;16>e;e+=2,d-=8)f|=parseInt(b.substring(e,e+2),16)<<d;var g=y(f,c);c=0;e=16;for(d=24;24>e;e+=2,d-=8)c|=parseInt(b.substring(e,e+2),16)<<d;f=0;for(d=e=24;32>e;e+=2,d-=8)f|=parseInt(b.substring(e,e+2),16)<<d;return new O(g,y(f,c))}function Ka(b){b="number"===typeof b?b:parseInt(b,10);return new Date(b)}
Date.prototype.B=function(b){return b instanceof Date?this.valueOf()===b.valueOf():!1};Date.prototype.C=function(){return this.valueOf()};
function La(b,c){if(c&&!1===c.N||"undefined"==typeof l.a)if("undefined"!=typeof Uint8Array){if("undefined"!=typeof atob)var d=atob(b);else{b=String(b).replace(/=+$/,"");if(1==b.length%4)throw Error("'atob' failed: The string to be decoded is not correctly encoded.");c=0;for(var e,f=0,g="";e=b.charAt(f++);~e&&(d=c%4?64*d+e:e,c++%4)?g+=String.fromCharCode(255&d>>(-2*c&6)):0)e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(e);d=g}b=d.length;c=new Uint8Array(b);for(e=0;e<
b;e++)c[e]=d.charCodeAt(e);d=c}else d=L("b",b);else d=new l.a(b,"base64");return d}function Ma(b){return L("r",b)}function P(b,c){this.entries=b;this.type=c||0;this.l=0}P.prototype.next=function(){if(this.l<this.entries.length){var b=null;0===this.type?b=this.entries[this.l]:1===this.type?b=this.entries[this.l+1]:b=[this.entries[this.l],this.entries[this.l+1]];b={value:b,done:!1};this.l+=2;return b}return{value:null,done:!0}};P.prototype.next=P.prototype.next;P.prototype[Aa]=function(){return this};
function Q(b,c){this.map=b;this.type=c||0;this.keys=Na(this.map);this.l=0;this.g=null;this.a=0}Q.prototype.next=function(){if(this.l<this.map.size){null!=this.g&&this.a<this.g.length||(this.g=this.map.map[this.keys[this.l]],this.a=0);var b=null;0===this.type?b=this.g[this.a]:1===this.type?b=this.g[this.a+1]:b=[this.g[this.a],this.g[this.a+1]];b={value:b,done:!1};this.l++;this.a+=2;return b}return{value:null,done:!0}};Q.prototype.next=Q.prototype.next;Q.prototype[Aa]=function(){return this};
function Oa(b,c){if(b instanceof R&&Pa(c)){if(b.size!==c.size)return!1;for(var d in b.map)for(var e=b.map[d],f=0;f<e.length;f+=2)if(!u(e[f+1],c.get(e[f])))return!1;return!0}if(b instanceof S&&Pa(c)){if(b.size!==c.size)return!1;b=b.j;for(f=0;f<b.length;f+=2)if(!u(b[f+1],c.get(b[f])))return!1;return!0}if(null!=c&&"object"===typeof c&&(f=n(c),d=f.length,b.size===d)){for(e=0;e<d;e++){var g=f[e];if(!b.has(g)||!u(c[g],b.get(g)))return!1}return!0}return!1}
function Qa(b){return null==b?"null":ha.isArray(b)?"["+b.toString()+"]":ha.S(b)?'"'+b+'"':b.toString()}function Ra(b){var c=0,d="TransitMap {";b.forEach(function(e,f){d+=Qa(f)+" => "+Qa(e);c<b.size-1&&(d+=", ");c++});return d+"}"}function Sa(b){var c=0,d="TransitSet {";b.forEach(function(e){d+=Qa(e);c<b.size-1&&(d+=", ");c++});return d+"}"}function S(b){this.j=b;this.h=null;this.a=-1;this.size=b.length/2;this.g=0}S.prototype.toString=function(){return Ra(this)};S.prototype.inspect=function(){return this.toString()};
function Ta(b){if(b.h)throw Error("Invalid operation, already converted");if(8>b.size)return!1;b.g++;return 32<b.g?(b.h=T(b.j,!1,!0),b.j=[],!0):!1}S.prototype.clear=function(){this.a=-1;this.h?this.h.clear():this.j=[];this.size=0};S.prototype.clear=S.prototype.clear;S.prototype.keys=function(){return this.h?this.h.keys():new P(this.j,0)};S.prototype.keys=S.prototype.keys;S.prototype.s=function(){if(this.h)return this.h.s();for(var b=[],c=0,d=0;d<this.j.length;c++,d+=2)b[c]=this.j[d];return b};
S.prototype.keySet=S.prototype.s;S.prototype.entries=function(){return this.h?this.h.entries():new P(this.j,2)};S.prototype.entries=S.prototype.entries;S.prototype.values=function(){return this.h?this.h.values():new P(this.j,1)};S.prototype.values=S.prototype.values;S.prototype.forEach=function(b){if(this.h)this.h.forEach(b);else for(var c=0;c<this.j.length;c+=2)b(this.j[c+1],this.j[c])};S.prototype.forEach=S.prototype.forEach;
S.prototype.get=function(b,c){if(this.h)return this.h.get(b);if(Ta(this))return this.get(b);for(var d=0;d<this.j.length;d+=2)if(u(this.j[d],b))return this.j[d+1];return c};S.prototype.get=S.prototype.get;S.prototype.has=function(b){if(this.h)return this.h.has(b);if(Ta(this))return this.has(b);for(var c=0;c<this.j.length;c+=2)if(u(this.j[c],b))return!0;return!1};S.prototype.has=S.prototype.has;
S.prototype.set=function(b,c){this.a=-1;if(this.h)this.h.set(b,c),this.size=this.h.size;else{for(var d=0;d<this.j.length;d+=2)if(u(this.j[d],b)){this.j[d+1]=c;return}this.j.push(b);this.j.push(c);this.size++;32<this.size&&(this.h=T(this.j,!1,!0),this.j=null)}};S.prototype.set=S.prototype.set;S.prototype["delete"]=function(b){this.a=-1;if(this.h)return b=this.h.delete(b),this.size=this.h.size,b;for(var c=0;c<this.j.length;c+=2)if(u(this.j[c],b))return b=this.j[c+1],this.j.splice(c,2),this.size--,b};
S.prototype.D=function(){var b=T();this.forEach(function(c,d){b.set(d,c)});return b};S.prototype.clone=S.prototype.D;S.prototype[Aa]=function(){return this.entries()};S.prototype.C=function(){if(this.h)return this.h.C();-1===this.a&&(this.a=ra(this));return this.a};S.prototype.B=function(b){return this.h?Oa(this.h,b):Oa(this,b)};function R(b,c,d){this.map=c||{};this.a=b||[];this.size=d||0;this.g=-1}R.prototype.toString=function(){return Ra(this)};R.prototype.inspect=function(){return this.toString()};
R.prototype.clear=function(){this.g=-1;this.map={};this.a=[];this.size=0};R.prototype.clear=R.prototype.clear;function Na(b){return null!=b.a?b.a:n(b.map)}R.prototype["delete"]=function(b){this.g=-1;this.a=null;for(var c=v(b),d=this.map[c],e=0;e<d.length;e+=2)if(u(b,d[e]))return b=d[e+1],d.splice(e,2),0===d.length&&delete this.map[c],this.size--,b};R.prototype.entries=function(){return new Q(this,2)};R.prototype.entries=R.prototype.entries;
R.prototype.forEach=function(b){for(var c=Na(this),d=0;d<c.length;d++)for(var e=this.map[c[d]],f=0;f<e.length;f+=2)b(e[f+1],e[f],this)};R.prototype.forEach=R.prototype.forEach;R.prototype.get=function(b,c){var d=v(b);d=this.map[d];if(null!=d)for(c=0;c<d.length;c+=2){if(u(b,d[c]))return d[c+1]}else return c};R.prototype.get=R.prototype.get;R.prototype.has=function(b){var c=v(b);c=this.map[c];if(null!=c)for(var d=0;d<c.length;d+=2)if(u(b,c[d]))return!0;return!1};R.prototype.has=R.prototype.has;
R.prototype.keys=function(){return new Q(this,0)};R.prototype.keys=R.prototype.keys;R.prototype.s=function(){for(var b=Na(this),c=[],d=0;d<b.length;d++)for(var e=this.map[b[d]],f=0;f<e.length;f+=2)c.push(e[f]);return c};R.prototype.keySet=R.prototype.s;R.prototype.set=function(b,c){this.g=-1;var d=v(b),e=this.map[d];if(null==e)this.a&&this.a.push(d),this.map[d]=[b,c],this.size++;else{d=!0;for(var f=0;f<e.length;f+=2)if(u(c,e[f])){d=!1;e[f]=c;break}d&&(e.push(b),e.push(c),this.size++)}};
R.prototype.set=R.prototype.set;R.prototype.values=function(){return new Q(this,1)};R.prototype.values=R.prototype.values;R.prototype.D=function(){var b=T();this.forEach(function(c,d){b.set(d,c)});return b};R.prototype.clone=R.prototype.D;R.prototype[Aa]=function(){return this.entries()};R.prototype.C=function(){-1===this.g&&(this.g=ra(this));return this.g};R.prototype.B=function(b){return Oa(this,b)};
function T(b,c,d){b=b||[];c=!1===c?c:!0;if((!0!==d||!d)&&64>=b.length){if(c){var e=b;b=[];for(c=0;c<e.length;c+=2){var f=!1;for(d=0;d<b.length;d+=2)if(u(b[d],e[c])){b[d+1]=e[c+1];f=!0;break}f||(b.push(e[c]),b.push(e[c+1]))}}return new S(b)}e={};f=[];var g=0;for(c=0;c<b.length;c+=2){d=v(b[c]);var h=e[d];if(null==h)f.push(d),e[d]=[b[c],b[c+1]],g++;else{var p=!0;for(d=0;d<h.length;d+=2)if(u(h[d],b[c])){h[d+1]=b[c+1];p=!1;break}p&&(h.push(b[c]),h.push(b[c+1]),g++)}}return new R(f,e,g)}
function Pa(b){return b instanceof S||b instanceof R}function U(b){this.map=b;this.size=b.size}U.prototype.toString=function(){return Sa(this)};U.prototype.inspect=function(){return this.toString()};U.prototype.add=function(b){this.map.set(b,b);this.size=this.map.size};U.prototype.add=U.prototype.add;U.prototype.clear=function(){this.map=new R;this.size=0};U.prototype.clear=U.prototype.clear;U.prototype["delete"]=function(b){b=this.map.delete(b);this.size=this.map.size;return b};
U.prototype.entries=function(){return this.map.entries()};U.prototype.entries=U.prototype.entries;U.prototype.forEach=function(b){var c=this;this.map.forEach(function(d,e){b(e,c)})};U.prototype.forEach=U.prototype.forEach;U.prototype.has=function(b){return this.map.has(b)};U.prototype.has=U.prototype.has;U.prototype.keys=function(){return this.map.keys()};U.prototype.keys=U.prototype.keys;U.prototype.g=function(){return this.map.s()};U.prototype.keySet=U.prototype.g;U.prototype.values=function(){return this.map.values()};
U.prototype.values=U.prototype.values;U.prototype.a=function(){var b=Ua();this.forEach(function(c){b.add(c)});return b};U.prototype.clone=U.prototype.a;U.prototype[Aa]=function(){return this.values()};U.prototype.B=function(b){if(b instanceof U){if(this.size===b.size)return u(this.map,b.map)}else return!1};U.prototype.C=function(){return v(this.map)};
function Ua(b){b=b||[];for(var c={},d=[],e=0,f=0;f<b.length;f++){var g=v(b[f]),h=c[g];if(null==h)d.push(g),c[g]=[b[f],b[f]],e++;else{g=!0;for(var p=0;p<h.length;p+=2)if(u(h[p],b[f])){g=!1;break}g&&(h.push(b[f]),h.push(b[f]),e++)}}return new U(new R(d,c,e))}function Va(b){return L("'",b)}function Wa(b){return L("list",b)}function Xa(b){return L("link",b)};function Ya(b){this.J=b}
function V(b){this.s=b||{};this.v={};for(var c in this.G.v)this.v[c]=this.G.v[c];for(c in this.s.handlers){a:{switch(c){case "_":case "s":case "?":case "i":case "d":case "b":case "'":case "array":case "map":b=!0;break a}b=!1}if(b)throw Error('Cannot override handler for ground type "'+c+'"');this.v[c]=this.s.handlers[c]}this.I=null!=this.s.preferStrings?this.s.preferStrings:this.G.I;this.N=null!=this.s.preferBuffers?this.s.preferBuffers:this.G.N;this.L=this.s.defaultHandler||this.G.L;this.g=this.s.mapBuilder;
this.D=this.s.arrayBuilder}
V.prototype.G={v:{_:function(){return null},"?":function(b){return"t"===b},b:function(b,c){return La(b,c)},i:function(b){return Da(b)},n:function(b){return Ea(b)},d:function(b){return parseFloat(b)},f:function(b){return Fa(b)},c:function(b){return b},":":function(b){return Ga(b)},$:function(b){return Ha(b)},r:function(b){return Ma(b)},z:function(b){a:switch(b){case "-INF":b=-Infinity;break a;case "INF":b=Infinity;break a;case "NaN":b=NaN;break a;default:throw Error("Invalid special double value "+b);
}return b},"'":function(b){return b},m:function(b){return Ka(b)},t:function(b){return new Date(b)},u:function(b){return Ja(b)},set:function(b){return Ua(b)},list:function(b){return Wa(b)},link:function(b){return Xa(b)},cmap:function(b){return T(b,!1)}},L:function(b,c){return L(b,c)},I:!0,N:!0};
V.prototype.a=function(b,c,d,e){if(null==b)return null;switch(typeof b){case "string":return ka(b,d)?(b=Za(this,b),c&&c.write(b,d),c=b):c="^"===b.charAt(0)&&" "!==b.charAt(1)?c.read(b,d):Za(this,b),c;case "object":if(q(b))if("^ "===b[0])if(this.g)if(17>b.length&&this.g.fromArray){e=[];for(d=1;d<b.length;d+=2)e.push(this.a(b[d],c,!0,!1)),e.push(this.a(b[d+1],c,!1,!1));c=this.g.fromArray(e,b)}else{e=this.g.init(b);for(d=1;d<b.length;d+=2)e=this.g.add(e,this.a(b[d],c,!0,!1),this.a(b[d+1],c,!1,!1),b);
c=this.g.finalize(e,b)}else{e=[];for(d=1;d<b.length;d+=2)e.push(this.a(b[d],c,!0,!1)),e.push(this.a(b[d+1],c,!1,!1));c=T(e,!1)}else c=$a(this,b,c,d,e);else{d=n(b);var f=d[0];if((e=1==d.length?this.a(f,c,!1,!1):null)&&e instanceof Ya)b=b[f],d=this.v[e.J],c=null!=d?d(this.a(b,c,!1,!0),this):L(e.J,this.a(b,c,!1,!1));else if(this.g)if(16>d.length&&this.g.fromArray){var g=[];for(e=0;e<d.length;e++)f=d[e],g.push(this.a(f,c,!0,!1)),g.push(this.a(b[f],c,!1,!1));c=this.g.fromArray(g,b)}else{g=this.g.init(b);
for(e=0;e<d.length;e++)f=d[e],g=this.g.add(g,this.a(f,c,!0,!1),this.a(b[f],c,!1,!1),b);c=this.g.finalize(g,b)}else{g=[];for(e=0;e<d.length;e++)f=d[e],g.push(this.a(f,c,!0,!1)),g.push(this.a(b[f],c,!1,!1));c=T(g,!1)}}return c}return b};V.prototype.decode=V.prototype.a;
function $a(b,c,d,e,f){if(f){var g=[];for(f=0;f<c.length;f++)g.push(b.a(c[f],d,e,!1));return g}g=d&&d.l;if(2===c.length&&"string"===typeof c[0]&&(f=b.a(c[0],d,!1,!1))&&f instanceof Ya)return c=c[1],g=b.v[f.J],null!=g?g=g(b.a(c,d,e,!0),b):L(f.J,b.a(c,d,e,!1));d&&g!=d.l&&(d.l=g);if(b.D){if(32>=c.length&&b.D.fromArray){g=[];for(f=0;f<c.length;f++)g.push(b.a(c[f],d,e,!1));return b.D.fromArray(g,c)}g=b.D.init(c);for(f=0;f<c.length;f++)g=b.D.add(g,b.a(c[f],d,e,!1),c);return b.D.finalize(g,c)}g=[];for(f=
0;f<c.length;f++)g.push(b.a(c[f],d,e,!1));return g}function Za(b,c){if("~"===c.charAt(0)){var d=c.charAt(1);if("~"===d||"^"===d||"`"===d)return c.substring(1);if("#"===d)return new Ya(c.substring(2));var e=b.v[d];return null==e?b.L(d,c.substring(2)):e(c.substring(2),b)}return c};function ab(b){this.a=new V(b)}function bb(b,c){this.g=b;this.a=c||{};this.cache=this.a.cache?this.a.cache:new t}bb.prototype.read=function(b){var c=this.cache;b=this.g.a.a(JSON.parse(b),c);this.cache.clear();return b};bb.prototype.read=bb.prototype.read;var cb=0,db="transit$guid$"+ja();function eb(b){if(null==b)return"null";if(b===String)return"string";if(b===Boolean)return"boolean";if(b===Number)return"number";if(b===Array)return"array";if(b===Object)return"map";var c=b[db];null==c&&("undefined"!=typeof Object.defineProperty?(c=++cb,Object.defineProperty(b,db,{value:c,enumerable:!1})):b[db]=c=++cb);return c}function W(b,c){b=b.toString();for(var d=b.length;d<c;d++)b="0"+b;return b}function fb(){}fb.prototype.tag=function(){return"_"};
fb.prototype.rep=function(){return null};fb.prototype.A=function(){return"null"};function gb(){}gb.prototype.tag=function(){return"s"};gb.prototype.rep=function(b){return b};gb.prototype.A=function(b){return b};function hb(){}hb.prototype.tag=function(){return"i"};hb.prototype.rep=function(b){return b};hb.prototype.A=function(b){return b.toString()};function ib(){}ib.prototype.tag=function(){return"i"};ib.prototype.rep=function(b){return b.toString()};ib.prototype.A=function(b){return b.toString()};
function jb(){}jb.prototype.tag=function(){return"?"};jb.prototype.rep=function(b){return b};jb.prototype.A=function(b){return b.toString()};function kb(){}kb.prototype.tag=function(){return"array"};kb.prototype.rep=function(b){return b};kb.prototype.A=function(){return null};function lb(){}lb.prototype.tag=function(){return"map"};lb.prototype.rep=function(b){return b};lb.prototype.A=function(){return null};function mb(){}mb.prototype.tag=function(){return"t"};
mb.prototype.rep=function(b){return b.getUTCFullYear()+"-"+W(b.getUTCMonth()+1,2)+"-"+W(b.getUTCDate(),2)+"T"+W(b.getUTCHours(),2)+":"+W(b.getUTCMinutes(),2)+":"+W(b.getUTCSeconds(),2)+"."+W(b.getUTCMilliseconds(),3)+"Z"};mb.prototype.A=function(b,c){return c.rep(b)};function nb(){}nb.prototype.tag=function(){return"m"};nb.prototype.rep=function(b){return b.valueOf()};nb.prototype.A=function(b){return b.valueOf().toString()};nb.prototype.O=function(){return new mb};function ob(){}
ob.prototype.tag=function(){return"u"};ob.prototype.rep=function(b){return b.toString()};ob.prototype.A=function(b){return b.toString()};function pb(){}pb.prototype.tag=function(){return":"};pb.prototype.rep=function(b){return b.o};pb.prototype.A=function(b,c){return c.rep(b)};function qb(){}qb.prototype.tag=function(){return"$"};qb.prototype.rep=function(b){return b.o};qb.prototype.A=function(b,c){return c.rep(b)};function rb(){}rb.prototype.tag=function(b){return b.tag};rb.prototype.rep=function(b){return b.rep};
rb.prototype.A=function(){return null};function sb(){}sb.prototype.tag=function(){return"set"};sb.prototype.rep=function(b){var c=[];b.forEach(function(d){c.push(d)});return L("array",c)};sb.prototype.A=function(){return null};function tb(){}tb.prototype.tag=function(){return"map"};tb.prototype.rep=function(b){return b};tb.prototype.A=function(){return null};function ub(){}ub.prototype.tag=function(){return"map"};ub.prototype.rep=function(b){return b};ub.prototype.A=function(){return null};
function vb(){}vb.prototype.tag=function(){return"b"};vb.prototype.rep=function(b){return b.toString("base64")};vb.prototype.A=function(){return null};function wb(){}wb.prototype.tag=function(){return"b"};
wb.prototype.rep=function(b){for(var c,d=0,e=b.length,f="",g;d<e;)g=b.subarray(d,Math.min(d+32768,e)),f+=String.fromCharCode.apply(null,g),d+=32768;if("undefined"!=typeof btoa)c=btoa(f);else{b=String(f);e=0;f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";for(g="";b.charAt(e|0)||(f="=",e%1);g+=f.charAt(63&c>>8-e%1*8)){d=b.charCodeAt(e+=.75);if(255<d)throw Error("'btoa' failed: The string to be encoded contains characters outside of the Latin1 range.");c=c<<8|d}c=g}return c};
wb.prototype.A=function(){return null};function xb(){this.v={};this.set(null,new fb);this.set(String,new gb);this.set(Number,new hb);this.set(w,new ib);this.set(Boolean,new jb);this.set(Array,new kb);this.set(Object,new lb);this.set(Date,new nb);this.set(O,new ob);this.set(M,new pb);this.set(N,new qb);this.set(K,new rb);this.set(U,new sb);this.set(S,new tb);this.set(R,new ub);"undefined"!=typeof l.a&&this.set(l.a,new vb);"undefined"!=typeof Uint8Array&&this.set(Uint8Array,new wb)}
xb.prototype.get=function(b){b="string"===typeof b?this.v[b]:this.v[eb(b)];return null!=b?b:this.v["default"]};xb.prototype.get=xb.prototype.get;xb.prototype.set=function(b,c){var d;if(d="string"===typeof b)a:{switch(b){case "null":case "string":case "boolean":case "number":case "array":case "map":d=!1;break a}d=!0}d?this.v[b]=c:this.v[eb(b)]=c};function yb(b){this.a=b||{};this.I=null!=this.a.preferStrings?this.a.preferStrings:!0;this.P=this.a.objectBuilder||null;this.transform=this.a.transform||null;this.v=new xb;if(b=this.a.handlers){if(q(b)||!b.forEach)throw Error('transit writer "handlers" option must be a map');var c=this;b.forEach(function(d,e){if(void 0!==e)c.v.set(e,d);else throw Error("Cannot create handler for JavaScript undefined");})}this.F=this.a.handlerForForeign;this.K=this.a.unpack||function(d){return d instanceof S&&null===
d.h?d.j:!1};this.H=this.a&&this.a.verbose||!1}function zb(b,c){var d=b.v.get(null==c?null:c.constructor);return null!=d?d:(c=c&&c.transitTag)?b.v.get(c):null}function X(b,c,d,e,f){b=b+c+d;return f?f.write(b,e):b}function Ab(b,c,d){var e=[];if(q(c))for(var f=0;f<c.length;f++)e.push(Y(b,c[f],!1,d));else c.forEach(function(g){e.push(Y(b,g,!1,d))});return e}function Bb(b,c){return"string"!==typeof c?(b=zb(b,c))&&1===b.tag(c).length:!0}
function Cb(b,c){var d=b.K(c),e=!0;if(d){for(c=0;c<d.length&&(e=Bb(b,d[c]),e);c+=2);return e}if(c.keys){d=c.keys();var f=null;if(d.next){for(f=d.next();!f.done;){e=Bb(b,f.value);if(!e)break;f=d.next()}return e}}if(c.forEach)return c.forEach(function(g,h){e=e&&Bb(b,h)}),e;throw Error("Cannot walk keys of object type "+(null==c?null:c.constructor).name);}
function Db(b){if(b.constructor.transit$isObject)return!0;var c=b.constructor.toString();c=c.substr(9);c=c.substr(0,c.indexOf("("));c="Object"==c;"undefined"!=typeof Object.defineProperty?Object.defineProperty(b.constructor,"transit$isObject",{value:c,enumerable:!1}):b.constructor.transit$isObject=c;return c}
function Eb(b,c,d){var e=null,f=null,g=null;e=null;var h=0;if(c.constructor===Object||null!=c.forEach||b.F&&Db(c)){if(b.H){if(null!=c.forEach){if(Cb(b,c)){var p={};c.forEach(function(z,A){p[Y(b,A,!0,!1)]=Y(b,z,!1,d)});return p}e=b.K(c);f=[];g=X("~#","cmap","",!0,d);if(e)for(;h<e.length;h+=2)f.push(Y(b,e[h],!1,!1)),f.push(Y(b,e[h+1],!1,d));else c.forEach(function(z,A){f.push(Y(b,A,!1,!1));f.push(Y(b,z,!1,d))});p={};p[g]=f;return p}e=n(c);for(p={};h<e.length;h++)p[Y(b,e[h],!0,!1)]=Y(b,c[e[h]],!1,d);
return p}if(null!=c.forEach){if(Cb(b,c)){e=b.K(c);p=["^ "];if(e)for(;h<e.length;h+=2)p.push(Y(b,e[h],!0,d)),p.push(Y(b,e[h+1],!1,d));else c.forEach(function(z,A){p.push(Y(b,A,!0,d));p.push(Y(b,z,!1,d))});return p}e=b.K(c);f=[];g=X("~#","cmap","",!0,d);if(e)for(;h<e.length;h+=2)f.push(Y(b,e[h],!1,d)),f.push(Y(b,e[h+1],!1,d));else c.forEach(function(z,A){f.push(Y(b,A,!1,d));f.push(Y(b,z,!1,d))});return[g,f]}p=["^ "];for(e=n(c);h<e.length;h++)p.push(Y(b,e[h],!0,d)),p.push(Y(b,c[e[h]],!1,d));return p}if(null!=
b.P)return b.P(c,function(z){return Y(b,z,!0,d)},function(z){return Y(b,z,!1,d)});h=(null==c?null:c.constructor).name;e=Error("Cannot write "+h);e.data={M:c,type:h};throw e;}
function Y(b,c,d,e){null!==b.transform&&(c=b.transform(c));var f=zb(b,c)||(b.F?b.F(c,b.v):null),g=f?f.tag(c):null,h=f?f.rep(c):null;if(null!=f&&null!=g)switch(g){case "_":return d?X("~","_","",d,e):null;case "s":return 0<h.length?(b=h.charAt(0),b="~"===b||"^"===b||"`"===b?"~"+h:h):b=h,X("","",b,d,e);case "?":return d?X("~","?",h.toString()[0],d,e):h;case "i":return Infinity===h?X("~","z","INF",d,e):-Infinity===h?X("~","z","-INF",d,e):isNaN(h)?X("~","z","NaN",d,e):d||"string"===typeof h||h instanceof
w?X("~","i",h.toString(),d,e):h;case "d":return d?X(h.R,"d",h,d,e):h;case "b":return X("~","b",h,d,e);case "'":return b.H?(d={},c=X("~#","'","",!0,e),d[c]=Y(b,h,!1,e),e=d):e=[X("~#","'","",!0,e),Y(b,h,!1,e)],e;case "array":return Ab(b,h,e);case "map":return Eb(b,h,e);default:a:{if(1===g.length){if("string"===typeof h){e=X("~",g,h,d,e);break a}if(d||b.I){(b=b.H&&f.O())?(g=b.tag(c),h=b.A(c,b)):h=f.A(c,f);if(null!==h){e=X("~",g,h,d,e);break a}e=Error('Tag "'+g+'" cannot be encoded as string');e.data=
{tag:g,rep:h,M:c};throw e;}}d=g;c=h;b.H?(f={},f[X("~#",d,"",!0,e)]=Y(b,c,!1,e),e=f):e=[X("~#",d,"",!0,e),Y(b,c,!1,e)]}return e}else throw e=(null==c?null:c.constructor).name,b=Error("Cannot write "+e),b.data={M:c,type:e},b;}function Fb(b,c){b=zb(b,c)||(b.F?b.F(c,b.v):null);if(null!=b)return 1===b.tag(c).length?Va(c):c;b=(null==c?null:c.constructor).name;var d=Error("Cannot write "+b);d.data={M:c,type:b};throw d;}
function Z(b,c){this.a=b;this.g=c||{};!1===this.g.cache?this.cache=null:this.cache=this.g.cache?this.g.cache:new ma}Z.prototype.s=function(){return this.a};Z.prototype.marshaller=Z.prototype.s;Z.prototype.write=function(b,c){var d=c||{};c=d.asMapKey||!1;var e=this.a.H?!1:this.cache;!1===d.marshalTop?b=Y(this.a,b,c,e):(d=this.a,b=JSON.stringify(Y(d,Fb(d,b),c,e)));null!=this.cache&&this.cache.clear();return b};Z.prototype.write=Z.prototype.write;Z.prototype.register=function(b,c){this.a.v.set(b,c)};
Z.prototype.register=Z.prototype.register;m("transit.reader",function(b,c){if("json"===b||"json-verbose"===b||null==b)return b=new ab(c),new bb(b,c);throw Error("Cannot create reader of type "+b);});m("transit.writer",function(b,c){if("json"===b||"json-verbose"===b||null==b)return"json-verbose"===b&&(null==c&&(c={}),c.verbose=!0),b=new yb(c),new Z(b,c);c=Error('Type must be "json"');c.data={type:b};throw c;});
m("transit.makeBuilder",function(b){function c(){}c.prototype.init=b.init;c.prototype.add=b.add;c.prototype.finalize=b.finalize;c.prototype.fromArray=b.fromArray;return new c});m("transit.makeWriteHandler",function(b){function c(){}c.prototype.tag=b.tag;c.prototype.rep=b.rep;c.prototype.A=b.stringRep;c.prototype.O=b.getVerboseHandler;return new c});m("transit.date",Ka);m("transit.integer",Da);
m("transit.isInteger",function(b){return b instanceof w?!0:"number"===typeof b&&!isNaN(b)&&Infinity!==b&&parseFloat(b)===parseInt(b,10)});m("transit.uuid",function(b){return Ja(b)});m("transit.isUUID",function(b){return b instanceof O});m("transit.bigInt",Ea);m("transit.isBigInt",function(b){return b instanceof K&&"n"===b.tag});m("transit.bigDec",Fa);m("transit.isBigDec",function(b){return b instanceof K&&"f"===b.tag});m("transit.keyword",Ga);m("transit.isKeyword",function(b){return b instanceof M});
m("transit.symbol",Ha);m("transit.isSymbol",function(b){return b instanceof N});m("transit.binary",La);m("transit.isBinary",function(b){return"undefined"!=typeof l.a&&b instanceof l.a?!0:"undefined"!=typeof Uint8Array&&b instanceof Uint8Array?!0:b instanceof K&&"b"===b.tag});m("transit.uri",Ma);m("transit.isURI",function(b){return b instanceof K&&"r"===b.tag});m("transit.map",T);m("transit.isMap",Pa);m("transit.set",Ua);m("transit.isSet",function(b){return b instanceof U});m("transit.list",Wa);
m("transit.isList",function(b){return b instanceof K&&"list"===b.tag});m("transit.quoted",Va);m("transit.isQuoted",function(b){return b instanceof K&&"'"===b.tag});m("transit.tagged",L);m("transit.isTaggedValue",function(b){return b instanceof K});m("transit.link",Xa);m("transit.isLink",function(b){return b instanceof K&&"link"===b.tag});m("transit.hash",v);m("transit.hashMapLike",ra);m("transit.hashArrayLike",sa);m("transit.equals",u);
m("transit.extendToEQ",function(b,c){b.C=c.hashCode;b.B=c.equals;return b});m("transit.mapToObject",function(b){var c={};b.forEach(function(d,e){if("string"!==typeof e)throw Error("Cannot convert map with non-string keys");c[e]=d});return c});m("transit.objectToMap",function(b){var c=T(),d;for(d in b)b.hasOwnProperty(d)&&c.set(d,b[d]);return c});m("transit.decoder",function(b){return new V(b)});m("transit.UUIDfromString",Ja);m("transit.randomUUID",ja);m("transit.stringableKeys",Cb);
m("transit.readCache",function(){return new t});m("transit.writeCache",function(){return new ma});})();
