// transit-js 0.8.867
// http://transit-format.org
// 
// Copyright 2014 Cognitect. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License..
;(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function b(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}}var m="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){if(a==Array.prototype||a==Object.prototype)return a;a[c]=d.value;return a};
function n(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var d=a[c];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");}var p=n(this);function t(a,c){if(c)a:{var d=p;a=a.split(".");for(var e=0;e<a.length-1;e++){var f=a[e];if(!(f in d))break a;d=d[f]}a=a[a.length-1];e=d[a];c=c(e);c!=e&&null!=c&&m(d,a,{configurable:!0,writable:!0,value:c})}}
t("Symbol",function(a){function c(f){if(this instanceof c)throw new TypeError("Symbol is not a constructor");return new d("jscomp_symbol_"+(f||"")+"_"+e++,f)}function d(f,h){this.g=f;m(this,"description",{configurable:!0,writable:!0,value:h})}if(a)return a;d.prototype.toString=function(){return this.g};var e=0;return c});
t("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var c="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<c.length;d++){var e=p[c[d]];"function"===typeof e&&"function"!=typeof e.prototype[a]&&m(e.prototype,a,{configurable:!0,writable:!0,value:function(){return v(b(this))}})}return a});function v(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function w(a,c){a instanceof String&&(a+="");var d=0,e={next:function(){if(d<a.length){var f=d++;return{value:c(f,a[f]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e}t("Array.prototype.entries",function(a){return a?a:function(){return w(this,function(c,d){return[c,d]})}});t("Array.prototype.keys",function(a){return a?a:function(){return w(this,function(c){return c})}});
t("Array.prototype.values",function(a){return a?a:function(){return w(this,function(c,d){return d})}});var x=x||{},y=this||self;var z={o:{}};z.o.W="undefined"!=typeof Object.keys?function(a){return Object.keys(a)}:function(a){var c=[],d=0,e;for(e in a)c[d++]=e;return c};z.o.isArray="undefined"!=typeof Array.isArray?function(a){return Array.isArray(a)}:function(a){var c=typeof a;return"array"===("object"!=c?c:a?Array.isArray(a)?"array":c:"null")};z.o.eb="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";z.o.ob=function(a){return Math.round(Math.random()*a)};z.o.G=function(){return z.o.ob(15).toString(16)};
z.o.randomUUID=function(){var a=(8|3&z.o.ob(14)).toString(16);return z.o.G()+z.o.G()+z.o.G()+z.o.G()+z.o.G()+z.o.G()+z.o.G()+z.o.G()+"-"+z.o.G()+z.o.G()+z.o.G()+z.o.G()+"-4"+z.o.G()+z.o.G()+z.o.G()+"-"+a+z.o.G()+z.o.G()+z.o.G()+"-"+z.o.G()+z.o.G()+z.o.G()+z.o.G()+z.o.G()+z.o.G()+z.o.G()+z.o.G()+z.o.G()+z.o.G()+z.o.G()+z.o.G()};
z.o.btoa=function(a){if("undefined"!=typeof btoa)return btoa(a);a=String(a);for(var c,d,e=0,f=z.o.eb,h="";a.charAt(e|0)||(f="=",e%1);h+=f.charAt(63&c>>8-e%1*8)){d=a.charCodeAt(e+=.75);if(255<d)throw Error("'btoa' failed: The string to be encoded contains characters outside of the Latin1 range.");c=c<<8|d}return h};
z.o.atob=function(a){if("undefined"!=typeof atob)return atob(a);a=String(a).replace(/=+$/,"");if(1==a.length%4)throw Error("'atob' failed: The string to be decoded is not correctly encoded.");for(var c=0,d,e,f=0,h="";e=a.charAt(f++);~e&&(d=c%4?64*d+e:e,c++%4)?h+=String.fromCharCode(255&d>>(-2*c&6)):0)e=z.o.eb.indexOf(e);return h};z.o.Ab=function(a){for(var c=0,d=a.length,e="",f;c<d;)f=a.subarray(c,Math.min(c+32768,d)),e+=String.fromCharCode.apply(null,f),c+=32768;return z.o.btoa(e)};
z.o.rb=function(a){a=z.o.atob(a);for(var c=a.length,d=new Uint8Array(c),e=0;e<c;e++)d[e]=a.charCodeAt(e);return d};z.D={};z.D.O="~";z.D.zb="#";z.D.ka="^";z.D.$a="`";z.D.aa="~#";z.v={};z.v.xb=3;z.v.fa=48;z.v.ga=44;z.v.Za=z.v.ga*z.v.ga;z.v.ub=4096;z.v.kb=function(a,c){if(a.length>z.v.xb){if(c)return!0;c=a.charAt(1);return a.charAt(0)===z.D.O?":"===c||"$"===c||"#"===c:!1}return!1};z.v.ib=function(a){var c=Math.floor(a/z.v.ga);a=String.fromCharCode(a%z.v.ga+z.v.fa);return 0===c?z.D.ka+a:z.D.ka+String.fromCharCode(c+z.v.fa)+a};z.v.Ia=function(){this.g=this.J=0;this.cache={}};
z.v.Ia.prototype.write=function(a,c){return z.v.kb(a,c)?(0===z.v.ub?(this.clear(),this.g=0,this.cache={}):this.J===z.v.Za&&this.clear(),c=this.cache[a],null==c?(this.cache[a]=[z.v.ib(this.J),this.g],this.J++,a):c[1]!=this.g?(c[1]=this.g,c[0]=z.v.ib(this.J),this.J++,a):c[0]):a};z.v.Ia.prototype.clear=function(){this.J=0;this.g++};z.v.writeCache=function(){return new z.v.Ia};z.v.Pb=function(a){return a.charAt(0)===z.D.ka&&" "!==a.charAt(1)};
z.v.Db=function(a){return 2===a.length?a.charCodeAt(1)-z.v.fa:(a.charCodeAt(1)-z.v.fa)*z.v.ga+(a.charCodeAt(2)-z.v.fa)};z.v.ja=function(){this.J=0;this.cache=[]};z.v.ja.prototype.write=function(a){this.J==z.v.Za&&(this.J=0);this.cache[this.J]=a;this.J++;return a};z.v.ja.prototype.read=function(a){return this.cache[z.v.Db(a)]};z.v.ja.prototype.clear=function(){this.J=0};z.v.readCache=function(){return new z.v.ja};z.j={};z.j.Pa="transit$hashCode$";z.j.hb=1;z.j.equals=function(a,c){if(null==a)return null==c;if(a===c)return!0;if("object"===typeof a){if(z.o.isArray(a)){if(z.o.isArray(c)&&a.length===c.length){for(var d=0;d<a.length;d++)if(!z.j.equals(a[d],c[d]))return!1;return!0}return!1}if(a.P)return a.P(c);if(null!=c&&"object"===typeof c){if(c.P)return c.P(a);d=0;var e=z.o.W(c).length,f;for(f in a)if(a.hasOwnProperty(f)&&(d++,!c.hasOwnProperty(f)||!z.j.equals(a[f],c[f])))return!1;return d===e}}return!1};
z.j.Qa=function(a,c){return a^c+2654435769+(a<<6)+(a>>2)};z.j.Va={};z.j.Wa=0;z.j.yb=256;z.j.Lb=function(a){var c=z.j.Va[a];if(null!=c)return c;for(var d=c=0;d<a.length;++d)c=31*c+a.charCodeAt(d),c%=4294967296;z.j.Wa++;z.j.Wa>=z.j.yb&&(z.j.Va={},z.j.Wa=1);return z.j.Va[a]=c};z.j.hashMapLike=function(a){var c=0;if(null!=a.forEach)a.forEach(function(k,l){c=(c+(z.j.s(l)^z.j.s(k)))%4503599627370496});else for(var d=z.o.W(a),e=0;e<d.length;e++){var f=d[e],h=a[f];c=(c+(z.j.s(f)^z.j.s(h)))%4503599627370496}return c};
z.j.hashArrayLike=function(a){var c=0;if(z.o.isArray(a))for(var d=0;d<a.length;d++)c=z.j.Qa(c,z.j.s(a[d]));else a.forEach&&a.forEach(function(e){c=z.j.Qa(c,z.j.s(e))});return c};
z.j.s=function(a){if(null==a)return 0;switch(typeof a){case "number":return a;case "boolean":return!0===a?1:0;case "string":return z.j.Lb(a);case "function":var c=a[z.j.Pa];if(c)return c;c=z.j.hb;"undefined"!=typeof Object.defineProperty?Object.defineProperty(a,z.j.Pa,{value:c,enumerable:!1}):a[z.j.Pa]=c;z.j.hb++;return c;default:return a instanceof Date?a.valueOf():z.o.isArray(a)?z.j.hashArrayLike(a):a.S?a.S():z.j.hashMapLike(a)}};z.j.extendToEQ=function(a,c){a.S=c.hashCode;a.P=c.equals;return a};function A(a,c){this.l=a|0;this.g=c|0}function B(a){return 4294967296*a.g+(a.l>>>0)}
A.prototype.toString=function(a){a=a||10;if(2>a||36<a)throw Error("radix out of range: "+a);var c=this.g>>21;if(0==c||-1==c&&(0!=this.l||-2097152!=this.g))return c=B(this),10==a?""+c:c.toString(a);c=14-(a>>2);var d=Math.pow(a,c),e=C(d,d/4294967296);d=D(this,e);e=Math.abs(B(this.add(E(G(d,e)))));var f=10==a?""+e:e.toString(a);f.length<c&&(f="0000000000000".substr(f.length-c)+f);e=B(d);return(10==a?e:e.toString(a))+f};function H(a){return 0==a.l&&0==a.g}
A.prototype.equals=function(a){return this.l==a.l&&this.g==a.g};function I(a,c){return a.g==c.g?a.l==c.l?0:a.l>>>0>c.l>>>0?1:-1:a.g>c.g?1:-1}function E(a){var c=~a.l+1|0;return C(c,~a.g+!c|0)}A.prototype.add=function(a){var c=this.g>>>16,d=this.g&65535,e=this.l>>>16,f=a.g>>>16,h=a.g&65535,k=a.l>>>16;a=(this.l&65535)+(a.l&65535);k=(a>>>16)+(e+k);e=k>>>16;e+=d+h;c=(e>>>16)+(c+f)&65535;return C((k&65535)<<16|a&65535,c<<16|e&65535)};
function G(a,c){if(H(a))return a;if(H(c))return c;var d=a.g>>>16,e=a.g&65535,f=a.l>>>16;a=a.l&65535;var h=c.g>>>16,k=c.g&65535,l=c.l>>>16;c=c.l&65535;var q=a*c;var r=(q>>>16)+f*c;var u=r>>>16;r=(r&65535)+a*l;u+=r>>>16;u+=e*c;var F=u>>>16;u=(u&65535)+f*l;F+=u>>>16;u=(u&65535)+a*k;F=F+(u>>>16)+(d*c+e*l+f*k+a*h)&65535;return C((r&65535)<<16|q&65535,F<<16|u&65535)}
function D(a,c){if(H(c))throw Error("division by zero");if(0>a.g){if(a.equals(J)){if(c.equals(K)||c.equals(L))return J;if(c.equals(J))return K;var d=1;if(0==d)d=a;else{var e=a.g;d=32>d?C(a.l>>>d|e<<32-d,e>>d):C(e>>d-32,0<=e?0:-1)}d=M(D(d,c),1);if(d.equals(N))return 0>c.g?K:L;a=a.add(E(G(c,d)));return d.add(D(a,c))}return 0>c.g?D(E(a),E(c)):E(D(E(a),c))}if(H(a))return N;if(0>c.g)return c.equals(J)?N:E(D(a,E(c)));for(e=N;0<=I(a,c);){d=Math.max(1,Math.floor(B(a)/B(c)));var f=Math.ceil(Math.log(d)/Math.LN2);
f=48>=f?1:Math.pow(2,f-48);for(var h=O(d),k=G(h,c);0>k.g||0<I(k,a);)d-=f,h=O(d),k=G(h,c);H(h)&&(h=K);e=e.add(h);a=a.add(E(k))}return e}A.prototype.and=function(a){return C(this.l&a.l,this.g&a.g)};A.prototype.or=function(a){return C(this.l|a.l,this.g|a.g)};A.prototype.xor=function(a){return C(this.l^a.l,this.g^a.g)};function M(a,c){c&=63;if(0==c)return a;var d=a.l;return 32>c?C(d<<c,a.g<<c|d>>>32-c):C(0,d<<c-32)}
function P(a,c){c&=63;if(0==c)return a;var d=a.g;return 32>c?C(a.l>>>c|d<<32-c,d>>>c):32==c?C(d,0):C(d>>>c-32,0)}function O(a){return 0<a?0x7fffffffffffffff<=a?Q:new A(a,a/4294967296):0>a?-9223372036854775808>=a?J:E(new A(-a,-a/4294967296)):N}function C(a,c){return new A(a,c)}
function R(a,c){if("-"==a.charAt(0))return E(R(a.substring(1),c));var d=parseInt(a,c||10);if(9007199254740991>=d)return new A(d%4294967296|0,d/4294967296|0);if(0==a.length)throw Error("number format error: empty string");if(0<=a.indexOf("-"))throw Error('number format error: interior "-" character: '+a);c=c||10;if(2>c||36<c)throw Error("radix out of range: "+c);d=O(Math.pow(c,8));for(var e=N,f=0;f<a.length;f+=8){var h=Math.min(8,a.length-f),k=parseInt(a.substring(f,f+h),c);8>h?e=G(e,O(Math.pow(c,
h))).add(O(k)):(e=G(e,d),e=e.add(O(k)))}return e}var N=C(0,0),K=C(1,0),L=C(-1,-1),Q=C(4294967295,2147483647),J=C(0,2147483648);z.types={};"undefined"!=typeof Symbol?z.types.ba=Symbol.iterator:z.types.ba="@@iterator";z.types.N=function(a,c){this.tag=a;this.rep=c;this.s=-1};z.types.N.prototype.toString=function(){return"[TaggedValue: "+this.tag+", "+this.rep+"]"};z.types.N.prototype.g=function(a){return z.j.equals(this,a)};z.types.N.prototype.equiv=z.types.N.prototype.g;z.types.N.prototype.P=function(a){return a instanceof z.types.N?this.tag===a.tag&&z.j.equals(this.rep,a.rep):!1};
z.types.N.prototype.S=function(){-1===this.s&&(this.s=z.j.Qa(z.j.s(this.tag),z.j.s(this.rep)));return this.s};z.types.T=function(a,c){return new z.types.N(a,c)};z.types.isTaggedValue=function(a){return a instanceof z.types.N};z.types.$b=function(){return null};z.types.Bb=function(a){return"t"===a};z.types.vb=R("9007199254740991");z.types.wb=R("-9007199254740991");
z.types.jb=function(a){if("number"===typeof a)return a;if(a instanceof A)return a;a=R(a,10);var c;(c=0<I(a,z.types.vb))||(c=0>I(a,z.types.wb));return c?a:B(a)};A.prototype.M=function(a){return z.j.equals(this,a)};A.prototype.equiv=A.prototype.M;A.prototype.P=function(a){return a instanceof A&&this.equals(a)};A.prototype.S=function(){return this.l};z.types.isInteger=function(a){return a instanceof A?!0:"number"===typeof a&&!isNaN(a)&&Infinity!==a&&parseFloat(a)===parseInt(a,10)};z.types.Kb=function(a){return parseFloat(a)};
z.types.cb=function(a){return z.types.T("n",a)};z.types.Ob=function(a){return a instanceof z.types.N&&"n"===a.tag};z.types.bb=function(a){return z.types.T("f",a)};z.types.Nb=function(a){return a instanceof z.types.N&&"f"===a.tag};z.types.Cb=function(a){return a};z.types.R=function(a){this.K=a;this.s=-1};z.types.R.prototype.toString=function(){return":"+this.K};z.types.R.prototype.namespace=function(){var a=this.K.indexOf("/");return-1!=a?this.K.substring(0,a):null};
z.types.R.prototype.name=function(){var a=this.K.indexOf("/");return-1!=a?this.K.substring(a+1,this.K.length):this.K};z.types.R.prototype.g=function(a){return z.j.equals(this,a)};z.types.R.prototype.equiv=z.types.R.prototype.g;z.types.R.prototype.P=function(a){return a instanceof z.types.R&&this.K==a.K};z.types.R.prototype.S=function(){-1===this.s&&(this.s=z.j.s(this.K));return this.s};z.types.keyword=function(a){return new z.types.R(a)};z.types.isKeyword=function(a){return a instanceof z.types.R};
z.types.Symbol=function(a){this.K=a;this.s=-1};z.types.Symbol.prototype.namespace=function(){var a=this.K.indexOf("/");return-1!=a?this.K.substring(0,a):null};z.types.Symbol.prototype.name=function(){var a=this.K.indexOf("/");return-1!=a?this.K.substring(a+1,this.K.length):this.K};z.types.Symbol.prototype.toString=function(){return this.K};z.types.Symbol.prototype.g=function(a){return z.j.equals(this,a)};z.types.Symbol.prototype.equiv=z.types.Symbol.prototype.g;
z.types.Symbol.prototype.P=function(a){return a instanceof z.types.Symbol&&this.K==a.K};z.types.Symbol.prototype.S=function(){-1===this.s&&(this.s=z.j.s(this.K));return this.s};z.types.symbol=function(a){return new z.types.Symbol(a)};z.types.isSymbol=function(a){return a instanceof z.types.Symbol};z.types.ma=function(a,c,d){var e="";d=d||c+1;for(var f=8*(7-c),h=M(new A(255,0),f);c<d;c++,f-=8,h=P(h,8)){var k=P(a.and(h),f).toString(16);1==k.length&&(k="0"+k);e+=k}return e};
z.types.U=function(a,c){this.g=a;this.l=c;this.s=-1};z.types.U.prototype.toString=function(){var a=this.g,c=this.l;var d=z.types.ma(a,0,4)+"-";d+=z.types.ma(a,4,6)+"-";d+=z.types.ma(a,6,8)+"-";d+=z.types.ma(c,0,2)+"-";return d+=z.types.ma(c,2,8)};z.types.U.prototype.M=function(a){return z.j.equals(this,a)};z.types.U.prototype.equiv=z.types.U.prototype.M;z.types.U.prototype.P=function(a){return a instanceof z.types.U&&this.g.equals(a.g)&&this.l.equals(a.l)};
z.types.U.prototype.S=function(){-1===this.s&&(this.s=z.j.s(this.toString()));return this.s};z.types.UUIDfromString=function(a){a=a.replace(/-/g,"");var c,d;var e=c=0;for(d=24;8>e;e+=2,d-=8)c|=parseInt(a.substring(e,e+2),16)<<d;var f=0;e=8;for(d=24;16>e;e+=2,d-=8)f|=parseInt(a.substring(e,e+2),16)<<d;var h=C(f,c);c=0;e=16;for(d=24;24>e;e+=2,d-=8)c|=parseInt(a.substring(e,e+2),16)<<d;f=0;for(d=e=24;32>e;e+=2,d-=8)f|=parseInt(a.substring(e,e+2),16)<<d;return new z.types.U(h,C(f,c))};z.types.uuid=function(a){return z.types.UUIDfromString(a)};
z.types.isUUID=function(a){return a instanceof z.types.U};z.types.date=function(a){a="number"===typeof a?a:parseInt(a,10);return new Date(a)};z.types.Xb=function(a){return new Date(a)};Date.prototype.P=function(a){return a instanceof Date?this.valueOf()===a.valueOf():!1};Date.prototype.S=function(){return this.valueOf()};z.types.binary=function(a,c){return c&&!1===c.Ua||"undefined"==typeof y.g?"undefined"!=typeof Uint8Array?z.o.rb(a):z.types.T("b",a):new y.g(a,"base64")};
z.types.isBinary=function(a){return"undefined"!=typeof y.g&&a instanceof y.g?!0:"undefined"!=typeof Uint8Array&&a instanceof Uint8Array?!0:a instanceof z.types.N&&"b"===a.tag};z.types.uri=function(a){return z.types.T("r",a)};z.types.isURI=function(a){return a instanceof z.types.N&&"r"===a.tag};z.types.ca=0;z.types.Ga=1;z.types.Ya=2;z.types.X=function(a,c){this.entries=a;this.type=c||z.types.ca;this.J=0};
z.types.X.prototype.next=function(){if(this.J<this.entries.length){var a=null;this.type===z.types.ca?a=this.entries[this.J]:this.type===z.types.Ga?a=this.entries[this.J+1]:a=[this.entries[this.J],this.entries[this.J+1]];a={value:a,done:!1};this.J+=2;return a}return{value:null,done:!0}};z.types.X.prototype.next=z.types.X.prototype.next;z.types.X.prototype[z.types.ba]=function(){return this};
z.types.Y=function(a,c){this.map=a;this.type=c||z.types.ca;this.keys=S(this.map);this.J=0;this.l=null;this.g=0};z.types.Y.prototype.next=function(){if(this.J<this.map.size){null!=this.l&&this.g<this.l.length||(this.l=this.map.map[this.keys[this.J]],this.g=0);var a=null;this.type===z.types.ca?a=this.l[this.g]:this.type===z.types.Ga?a=this.l[this.g+1]:a=[this.l[this.g],this.l[this.g+1]];a={value:a,done:!1};this.J++;this.g+=2;return a}return{value:null,done:!0}};z.types.Y.prototype.next=z.types.Y.prototype.next;
z.types.Y.prototype[z.types.ba]=function(){return this};
z.types.Sa=function(a,c){if(a instanceof z.types.A&&z.types.isMap(c)){if(a.size!==c.size)return!1;for(var d in a.map)for(var e=a.map[d],f=0;f<e.length;f+=2)if(!z.j.equals(e[f+1],c.get(e[f])))return!1;return!0}if(a instanceof z.types.B&&z.types.isMap(c)){if(a.size!==c.size)return!1;a=a.H;for(f=0;f<a.length;f+=2)if(!z.j.equals(a[f+1],c.get(a[f])))return!1;return!0}if(null!=c&&"object"===typeof c&&(f=z.o.W(c),d=f.length,a.size===d)){for(e=0;e<d;e++){var h=f[e];if(!a.has(h)||!z.j.equals(c[h],a.get(h)))return!1}return!0}return!1};
z.types.Ma=8;z.types.Xa=32;z.types.qb=32;z.types.print=function(a){return null==a?"null":x.isArray(a)?"["+a.toString()+"]":x.Zb(a)?'"'+a+'"':a.toString()};z.types.nb=function(a){var c=0,d="TransitMap {";a.forEach(function(e,f){d+=z.types.print(f)+" => "+z.types.print(e);c<a.size-1&&(d+=", ");c++});return d+"}"};z.types.Ub=function(a){var c=0,d="TransitSet {";a.forEach(function(e){d+=z.types.print(e);c<a.size-1&&(d+=", ");c++});return d+"}"};
z.types.B=function(a){this.H=a;this.F=null;this.s=-1;this.size=a.length/2;this.g=0};z.types.B.prototype.toString=function(){return z.types.nb(this)};z.types.B.prototype.inspect=function(){return this.toString()};function T(a){if(a.F)throw Error("Invalid operation, already converted");if(a.size<z.types.Ma)return!1;a.g++;return a.g>z.types.qb?(a.F=z.types.map(a.H,!1,!0),a.H=[],!0):!1}z.types.B.prototype.clear=function(){this.s=-1;this.F?this.F.clear():this.H=[];this.size=0};
z.types.B.prototype.clear=z.types.B.prototype.clear;z.types.B.prototype.keys=function(){return this.F?this.F.keys():new z.types.X(this.H,z.types.ca)};z.types.B.prototype.keys=z.types.B.prototype.keys;z.types.B.prototype.l=function(){if(this.F)return this.F.l();for(var a=[],c=0,d=0;d<this.H.length;c++,d+=2)a[c]=this.H[d];return a};z.types.B.prototype.keySet=z.types.B.prototype.l;z.types.B.prototype.entries=function(){return this.F?this.F.entries():new z.types.X(this.H,z.types.Ya)};
z.types.B.prototype.entries=z.types.B.prototype.entries;z.types.B.prototype.values=function(){return this.F?this.F.values():new z.types.X(this.H,z.types.Ga)};z.types.B.prototype.values=z.types.B.prototype.values;z.types.B.prototype.forEach=function(a){if(this.F)this.F.forEach(a);else for(var c=0;c<this.H.length;c+=2)a(this.H[c+1],this.H[c])};z.types.B.prototype.forEach=z.types.B.prototype.forEach;
z.types.B.prototype.get=function(a,c){if(this.F)return this.F.get(a);if(T(this))return this.get(a);for(var d=0;d<this.H.length;d+=2)if(z.j.equals(this.H[d],a))return this.H[d+1];return c};z.types.B.prototype.get=z.types.B.prototype.get;z.types.B.prototype.has=function(a){if(this.F)return this.F.has(a);if(T(this))return this.has(a);for(var c=0;c<this.H.length;c+=2)if(z.j.equals(this.H[c],a))return!0;return!1};z.types.B.prototype.has=z.types.B.prototype.has;
z.types.B.prototype.set=function(a,c){this.s=-1;if(this.F)this.F.set(a,c),this.size=this.F.size;else{for(var d=0;d<this.H.length;d+=2)if(z.j.equals(this.H[d],a)){this.H[d+1]=c;return}this.H.push(a);this.H.push(c);this.size++;this.size>z.types.Xa&&(this.F=z.types.map(this.H,!1,!0),this.H=null)}};z.types.B.prototype.set=z.types.B.prototype.set;
z.types.B.prototype["delete"]=function(a){this.s=-1;if(this.F)return a=this.F.delete(a),this.size=this.F.size,a;for(var c=0;c<this.H.length;c+=2)if(z.j.equals(this.H[c],a))return a=this.H[c+1],this.H.splice(c,2),this.size--,a};z.types.B.prototype.M=function(){var a=z.types.map();this.forEach(function(c,d){a.set(d,c)});return a};z.types.B.prototype.clone=z.types.B.prototype.M;z.types.B.prototype[z.types.ba]=function(){return this.entries()};
z.types.B.prototype.S=function(){if(this.F)return this.F.S();-1===this.s&&(this.s=z.j.hashMapLike(this));return this.s};z.types.B.prototype.P=function(a){return this.F?z.types.Sa(this.F,a):z.types.Sa(this,a)};z.types.A=function(a,c,d){this.map=c||{};this.g=a||[];this.size=d||0;this.s=-1};z.types.A.prototype.toString=function(){return z.types.nb(this)};z.types.A.prototype.inspect=function(){return this.toString()};z.types.A.prototype.clear=function(){this.s=-1;this.map={};this.g=[];this.size=0};
z.types.A.prototype.clear=z.types.A.prototype.clear;function S(a){return null!=a.g?a.g:z.o.W(a.map)}z.types.A.prototype["delete"]=function(a){this.s=-1;this.g=null;for(var c=z.j.s(a),d=this.map[c],e=0;e<d.length;e+=2)if(z.j.equals(a,d[e]))return a=d[e+1],d.splice(e,2),0===d.length&&delete this.map[c],this.size--,a};z.types.A.prototype.entries=function(){return new z.types.Y(this,z.types.Ya)};z.types.A.prototype.entries=z.types.A.prototype.entries;
z.types.A.prototype.forEach=function(a){for(var c=S(this),d=0;d<c.length;d++)for(var e=this.map[c[d]],f=0;f<e.length;f+=2)a(e[f+1],e[f],this)};z.types.A.prototype.forEach=z.types.A.prototype.forEach;z.types.A.prototype.get=function(a,c){var d=z.j.s(a);d=this.map[d];if(null!=d)for(c=0;c<d.length;c+=2){if(z.j.equals(a,d[c]))return d[c+1]}else return c};z.types.A.prototype.get=z.types.A.prototype.get;
z.types.A.prototype.has=function(a){var c=z.j.s(a);c=this.map[c];if(null!=c)for(var d=0;d<c.length;d+=2)if(z.j.equals(a,c[d]))return!0;return!1};z.types.A.prototype.has=z.types.A.prototype.has;z.types.A.prototype.keys=function(){return new z.types.Y(this,z.types.ca)};z.types.A.prototype.keys=z.types.A.prototype.keys;z.types.A.prototype.l=function(){for(var a=S(this),c=[],d=0;d<a.length;d++)for(var e=this.map[a[d]],f=0;f<e.length;f+=2)c.push(e[f]);return c};z.types.A.prototype.keySet=z.types.A.prototype.l;
z.types.A.prototype.set=function(a,c){this.s=-1;var d=z.j.s(a),e=this.map[d];if(null==e)this.g&&this.g.push(d),this.map[d]=[a,c],this.size++;else{d=!0;for(var f=0;f<e.length;f+=2)if(z.j.equals(c,e[f])){d=!1;e[f]=c;break}d&&(e.push(a),e.push(c),this.size++)}};z.types.A.prototype.set=z.types.A.prototype.set;z.types.A.prototype.values=function(){return new z.types.Y(this,z.types.Ga)};z.types.A.prototype.values=z.types.A.prototype.values;
z.types.A.prototype.M=function(){var a=z.types.map();this.forEach(function(c,d){a.set(d,c)});return a};z.types.A.prototype.clone=z.types.A.prototype.M;z.types.A.prototype[z.types.ba]=function(){return this.entries()};z.types.A.prototype.S=function(){-1===this.s&&(this.s=z.j.hashMapLike(this));return this.s};z.types.A.prototype.P=function(a){return z.types.Sa(this,a)};
z.types.map=function(a,c,d){a=a||[];c=!1===c?c:!0;if((!0!==d||!d)&&a.length<=2*z.types.Xa){if(c){var e=a;a=[];for(c=0;c<e.length;c+=2){var f=!1;for(d=0;d<a.length;d+=2)if(z.j.equals(a[d],e[c])){a[d+1]=e[c+1];f=!0;break}f||(a.push(e[c]),a.push(e[c+1]))}}return new z.types.B(a)}e={};f=[];var h=0;for(c=0;c<a.length;c+=2){d=z.j.s(a[c]);var k=e[d];if(null==k)f.push(d),e[d]=[a[c],a[c+1]],h++;else{var l=!0;for(d=0;d<k.length;d+=2)if(z.j.equals(k[d],a[c])){k[d+1]=a[c+1];l=!1;break}l&&(k.push(a[c]),k.push(a[c+
1]),h++)}}return new z.types.A(f,e,h)};z.types.Mb=function(a){return a instanceof z.types.B};z.types.isMap=function(a){return a instanceof z.types.B||a instanceof z.types.A};z.types.C=function(a){this.map=a;this.size=a.size};z.types.C.prototype.toString=function(){return z.types.Ub(this)};z.types.C.prototype.inspect=function(){return this.toString()};z.types.C.prototype.add=function(a){this.map.set(a,a);this.size=this.map.size};z.types.C.prototype.add=z.types.C.prototype.add;
z.types.C.prototype.clear=function(){this.map=new z.types.A;this.size=0};z.types.C.prototype.clear=z.types.C.prototype.clear;z.types.C.prototype["delete"]=function(a){a=this.map.delete(a);this.size=this.map.size;return a};z.types.C.prototype.entries=function(){return this.map.entries()};z.types.C.prototype.entries=z.types.C.prototype.entries;z.types.C.prototype.forEach=function(a){var c=this;this.map.forEach(function(d,e){a(e,c)})};z.types.C.prototype.forEach=z.types.C.prototype.forEach;
z.types.C.prototype.has=function(a){return this.map.has(a)};z.types.C.prototype.has=z.types.C.prototype.has;z.types.C.prototype.keys=function(){return this.map.keys()};z.types.C.prototype.keys=z.types.C.prototype.keys;z.types.C.prototype.l=function(){return this.map.l()};z.types.C.prototype.keySet=z.types.C.prototype.l;z.types.C.prototype.values=function(){return this.map.values()};z.types.C.prototype.values=z.types.C.prototype.values;
z.types.C.prototype.g=function(){var a=z.types.set();this.forEach(function(c){a.add(c)});return a};z.types.C.prototype.clone=z.types.C.prototype.g;z.types.C.prototype[z.types.ba]=function(){return this.values()};z.types.C.prototype.P=function(a){if(a instanceof z.types.C){if(this.size===a.size)return z.j.equals(this.map,a.map)}else return!1};z.types.C.prototype.S=function(){return z.j.s(this.map)};
z.types.set=function(a){a=a||[];for(var c={},d=[],e=0,f=0;f<a.length;f++){var h=z.j.s(a[f]),k=c[h];if(null==k)d.push(h),c[h]=[a[f],a[f]],e++;else{h=!0;for(var l=0;l<k.length;l+=2)if(z.j.equals(k[l],a[f])){h=!1;break}h&&(k.push(a[f]),k.push(a[f]),e++)}}return new z.types.C(new z.types.A(d,c,e))};z.types.isSet=function(a){return a instanceof z.types.C};z.types.quoted=function(a){return z.types.T("'",a)};z.types.isQuoted=function(a){return a instanceof z.types.N&&"'"===a.tag};
z.types.list=function(a){return z.types.T("list",a)};z.types.isList=function(a){return a instanceof z.types.N&&"list"===a.tag};z.types.link=function(a){return z.types.T("link",a)};z.types.isLink=function(a){return a instanceof z.types.N&&"link"===a.tag};z.types.Vb=function(a){switch(a){case "-INF":return-Infinity;case "INF":return Infinity;case "NaN":return NaN;default:throw Error("Invalid special double value "+a);}};z.h={};z.h.decoder={};z.h.decoder.ab=function(a){this.Ka=a};z.h.decoder.tag=function(a){return new z.h.decoder.ab(a)};z.h.decoder.lb=function(a){return a&&a instanceof z.h.decoder.ab};z.h.decoder.Rb=function(a){switch(a){case "_":case "s":case "?":case "i":case "d":case "b":case "'":case "array":case "map":return!0}return!1};
z.h.decoder.Z=function(a){this.M=a||{};this.a={};for(var c in this.na.a)this.a[c]=this.na.a[c];for(c in this.M.handlers){if(z.h.decoder.Rb(c))throw Error('Cannot override handler for ground type "'+c+'"');this.a[c]=this.M.handlers[c]}this.Ja=null!=this.M.preferStrings?this.M.preferStrings:this.na.Ja;this.Ua=null!=this.M.preferBuffers?this.M.preferBuffers:this.na.Ua;this.Oa=this.M.defaultHandler||this.na.Oa;this.l=this.M.mapBuilder;this.da=this.M.arrayBuilder};
z.h.decoder.Z.prototype.na={a:{_:function(){return null},"?":function(a){return z.types.Bb(a)},b:function(a,c){return z.types.binary(a,c)},i:function(a){return z.types.jb(a)},n:function(a){return z.types.cb(a)},d:function(a){return z.types.Kb(a)},f:function(a){return z.types.bb(a)},c:function(a){return z.types.Cb(a)},":":function(a){return z.types.keyword(a)},$:function(a){return z.types.symbol(a)},r:function(a){return z.types.uri(a)},z:function(a){return z.types.Vb(a)},"'":function(a){return a},
m:function(a){return z.types.date(a)},t:function(a){return z.types.Xb(a)},u:function(a){return z.types.uuid(a)},set:function(a){return z.types.set(a)},list:function(a){return z.types.list(a)},link:function(a){return z.types.link(a)},cmap:function(a){return z.types.map(a,!1)}},Oa:function(a,c){return z.types.T(a,c)},Ja:!0,Ua:!0};
z.h.decoder.Z.prototype.g=function(a,c,d,e){if(null==a)return null;switch(typeof a){case "string":return z.v.kb(a,d)?(a=U(this,a),c&&c.write(a,d),c=a):c=z.v.Pb(a)?c.read(a,d):U(this,a),c;case "object":if(z.o.isArray(a))if("^ "===a[0])if(this.l)if(a.length<2*z.types.Ma+1&&this.l.fromArray){e=[];for(d=1;d<a.length;d+=2)e.push(this.g(a[d],c,!0,!1)),e.push(this.g(a[d+1],c,!1,!1));c=this.l.fromArray(e,a)}else{e=this.l.init(a);for(d=1;d<a.length;d+=2)e=this.l.add(e,this.g(a[d],c,!0,!1),this.g(a[d+1],c,
!1,!1),a);c=this.l.finalize(e,a)}else{e=[];for(d=1;d<a.length;d+=2)e.push(this.g(a[d],c,!0,!1)),e.push(this.g(a[d+1],c,!1,!1));c=z.types.map(e,!1)}else c=V(this,a,c,d,e);else{d=z.o.W(a);var f=d[0];e=1==d.length?this.g(f,c,!1,!1):null;if(z.h.decoder.lb(e))a=a[f],d=this.a[e.Ka],c=null!=d?d(this.g(a,c,!1,!0),this):z.types.T(e.Ka,this.g(a,c,!1,!1));else if(this.l)if(d.length<2*z.types.Ma&&this.l.fromArray){var h=[];for(e=0;e<d.length;e++)f=d[e],h.push(this.g(f,c,!0,!1)),h.push(this.g(a[f],c,!1,!1));c=
this.l.fromArray(h,a)}else{h=this.l.init(a);for(e=0;e<d.length;e++)f=d[e],h=this.l.add(h,this.g(f,c,!0,!1),this.g(a[f],c,!1,!1),a);c=this.l.finalize(h,a)}else{h=[];for(e=0;e<d.length;e++)f=d[e],h.push(this.g(f,c,!0,!1)),h.push(this.g(a[f],c,!1,!1));c=z.types.map(h,!1)}}return c}return a};z.h.decoder.Z.prototype.decode=z.h.decoder.Z.prototype.g;
function V(a,c,d,e,f){if(f){var h=[];for(f=0;f<c.length;f++)h.push(a.g(c[f],d,e,!1));return h}h=d&&d.J;if(2===c.length&&"string"===typeof c[0]&&(f=a.g(c[0],d,!1,!1),z.h.decoder.lb(f)))return c=c[1],h=a.a[f.Ka],null!=h?h=h(a.g(c,d,e,!0),a):z.types.T(f.Ka,a.g(c,d,e,!1));d&&h!=d.J&&(d.J=h);if(a.da){if(32>=c.length&&a.da.fromArray){h=[];for(f=0;f<c.length;f++)h.push(a.g(c[f],d,e,!1));return a.da.fromArray(h,c)}h=a.da.init(c);for(f=0;f<c.length;f++)h=a.da.add(h,a.g(c[f],d,e,!1),c);return a.da.finalize(h,
c)}h=[];for(f=0;f<c.length;f++)h.push(a.g(c[f],d,e,!1));return h}function U(a,c){if(c.charAt(0)===z.D.O){var d=c.charAt(1);if(d===z.D.O||d===z.D.ka||d===z.D.$a)return c.substring(1);if(d===z.D.zb)return z.h.decoder.tag(c.substring(2));var e=a.a[d];return null==e?a.Oa(d,c.substring(2)):e(c.substring(2),a)}return c}z.h.decoder.decoder=function(a){return new z.h.decoder.Z(a)};z.h.reader={};z.h.reader.tb=function(a){this.decoder=new z.h.decoder.Z(a)};z.h.reader.xa=function(a,c){this.l=a;this.g=c||{};this.cache=this.g.cache?this.g.cache:new z.v.ja};z.h.reader.xa.prototype.read=function(a){var c=this.cache;a=this.l.decoder.g(JSON.parse(a),c);this.cache.clear();return a};z.h.reader.xa.prototype.read=z.h.reader.xa.prototype.read;z.a={};z.a.fb=0;z.a.Na="transit$guid$"+z.o.randomUUID();z.a.pb=function(a){if(null==a)return"null";if(a===String)return"string";if(a===Boolean)return"boolean";if(a===Number)return"number";if(a===Array)return"array";if(a===Object)return"map";var c=a[z.a.Na];null==c&&("undefined"!=typeof Object.defineProperty?(c=++z.a.fb,Object.defineProperty(a,z.a.Na,{value:c,enumerable:!1})):a[z.a.Na]=c=++z.a.fb);return c};z.a.constructor=function(a){return null==a?null:a.constructor};
z.a.ea=function(a,c){a=a.toString();for(var d=a.length;d<c;d++)a="0"+a;return a};z.a.stringableKeys=function(a){a=z.o.W(a);for(var c=0;c<a.length;c++);return!0};z.a.va=function(){};z.a.va.prototype.tag=function(){return"_"};z.a.va.prototype.rep=function(){return null};z.a.va.prototype.L=function(){return"null"};z.a.ya=function(){};z.a.ya.prototype.tag=function(){return"s"};z.a.ya.prototype.rep=function(a){return a};z.a.ya.prototype.L=function(a){return a};z.a.wa=function(){};
z.a.wa.prototype.tag=function(){return"i"};z.a.wa.prototype.rep=function(a){return a};z.a.wa.prototype.L=function(a){return a.toString()};z.a.sa=function(){};z.a.sa.prototype.tag=function(){return"i"};z.a.sa.prototype.rep=function(a){return a.toString()};z.a.sa.prototype.L=function(a){return a.toString()};z.a.qa=function(){};z.a.qa.prototype.tag=function(){return"?"};z.a.qa.prototype.rep=function(a){return a};z.a.qa.prototype.L=function(a){return a.toString()};z.a.pa=function(){};
z.a.pa.prototype.tag=function(){return"array"};z.a.pa.prototype.rep=function(a){return a};z.a.pa.prototype.L=function(){return null};z.a.ua=function(){};z.a.ua.prototype.tag=function(){return"map"};z.a.ua.prototype.rep=function(a){return a};z.a.ua.prototype.L=function(){return null};z.a.Ha=function(){};z.a.Ha.prototype.tag=function(){return"t"};
z.a.Ha.prototype.rep=function(a){return a.getUTCFullYear()+"-"+z.a.ea(a.getUTCMonth()+1,2)+"-"+z.a.ea(a.getUTCDate(),2)+"T"+z.a.ea(a.getUTCHours(),2)+":"+z.a.ea(a.getUTCMinutes(),2)+":"+z.a.ea(a.getUTCSeconds(),2)+"."+z.a.ea(a.getUTCMilliseconds(),3)+"Z"};z.a.Ha.prototype.L=function(a,c){return c.rep(a)};z.a.ha=function(){};z.a.ha.prototype.tag=function(){return"m"};z.a.ha.prototype.rep=function(a){return a.valueOf()};z.a.ha.prototype.L=function(a){return a.valueOf().toString()};
z.a.ha.prototype.gb=function(){return new z.a.Ha};z.a.Ea=function(){};z.a.Ea.prototype.tag=function(){return"u"};z.a.Ea.prototype.rep=function(a){return a.toString()};z.a.Ea.prototype.L=function(a){return a.toString()};z.a.ta=function(){};z.a.ta.prototype.tag=function(){return":"};z.a.ta.prototype.rep=function(a){return a.K};z.a.ta.prototype.L=function(a,c){return c.rep(a)};z.a.za=function(){};z.a.za.prototype.tag=function(){return"$"};z.a.za.prototype.rep=function(a){return a.K};
z.a.za.prototype.L=function(a,c){return c.rep(a)};z.a.Aa=function(){};z.a.Aa.prototype.tag=function(a){return a.tag};z.a.Aa.prototype.rep=function(a){return a.rep};z.a.Aa.prototype.L=function(){return null};z.a.Da=function(){};z.a.Da.prototype.tag=function(){return"set"};z.a.Da.prototype.rep=function(a){var c=[];a.forEach(function(d){c.push(d)});return z.types.T("array",c)};z.a.Da.prototype.L=function(){return null};z.a.Ba=function(){};z.a.Ba.prototype.tag=function(){return"map"};
z.a.Ba.prototype.rep=function(a){return a};z.a.Ba.prototype.L=function(){return null};z.a.Ca=function(){};z.a.Ca.prototype.tag=function(){return"map"};z.a.Ca.prototype.rep=function(a){return a};z.a.Ca.prototype.L=function(){return null};z.a.ra=function(){};z.a.ra.prototype.tag=function(){return"b"};z.a.ra.prototype.rep=function(a){return a.toString("base64")};z.a.ra.prototype.L=function(){return null};z.a.Fa=function(){};z.a.Fa.prototype.tag=function(){return"b"};z.a.Fa.prototype.rep=function(a){return z.o.Ab(a)};
z.a.Fa.prototype.L=function(){return null};
z.a.Eb=function(a){a.set(null,new z.a.va);a.set(String,new z.a.ya);a.set(Number,new z.a.wa);a.set(A,new z.a.sa);a.set(Boolean,new z.a.qa);a.set(Array,new z.a.pa);a.set(Object,new z.a.ua);a.set(Date,new z.a.ha);a.set(z.types.U,new z.a.Ea);a.set(z.types.R,new z.a.ta);a.set(z.types.Symbol,new z.a.za);a.set(z.types.N,new z.a.Aa);a.set(z.types.C,new z.a.Da);a.set(z.types.B,new z.a.Ba);a.set(z.types.A,new z.a.Ca);"undefined"!=typeof y.g&&a.set(y.g,new z.a.ra);"undefined"!=typeof Uint8Array&&a.set(Uint8Array,
new z.a.Fa)};z.a.ia=function(){this.a={};z.a.Eb(this)};z.a.ia.prototype.get=function(a){a="string"===typeof a?this.a[a]:this.a[z.a.pb(a)];return null!=a?a:this.a["default"]};z.a.ia.prototype.get=z.a.ia.prototype.get;z.a.Wb=function(a){switch(a){case "null":case "string":case "boolean":case "number":case "array":case "map":return!1}return!0};z.a.ia.prototype.set=function(a,c){"string"===typeof a&&z.a.Wb(a)?this.a[a]=c:this.a[z.a.pb(a)]=c};z.h.writer={};z.h.writer.escape=function(a){if(0<a.length){var c=a.charAt(0);return c===z.D.O||c===z.D.ka||c===z.D.$a?z.D.O+a:a}return a};
z.h.writer.sb=function(a){this.g=a||{};this.Ja=null!=this.g.preferStrings?this.g.preferStrings:!0;this.mb=this.g.objectBuilder||null;this.transform=this.g.transform||null;this.a=new z.a.ia;if(a=this.g.handlers){if(z.o.isArray(a)||!a.forEach)throw Error('transit writer "handlers" option must be a map');var c=this;a.forEach(function(d,e){if(void 0!==e)c.a.set(e,d);else throw Error("Cannot create handler for JavaScript undefined");})}this.la=this.g.handlerForForeign;this.La=this.g.unpack||function(d){return z.types.Mb(d)&&
null===d.F?d.H:!1};this.oa=this.g&&this.g.verbose||!1};function W(a,c){var d=a.a.get(z.a.constructor(c));return null!=d?d:(c=c&&c.transitTag)?a.a.get(c):null}function X(a,c,d,e,f){a=a+c+d;return f?f.write(a,e):a}z.h.writer.Ib=function(a,c,d){var e=[];if(z.o.isArray(c))for(var f=0;f<c.length;f++)e.push(z.h.writer.I(a,c[f],!1,d));else c.forEach(function(h){e.push(z.h.writer.I(a,h,!1,d))});return e};z.h.writer.Fb=function(a,c,d){return z.h.writer.Ib(a,c,d)};
z.h.writer.Ra=function(a,c){return"string"!==typeof c?(a=W(a,c))&&1===a.tag(c).length:!0};z.h.writer.stringableKeys=function(a,c){var d=a.La(c),e=!0;if(d){for(c=0;c<d.length&&(e=z.h.writer.Ra(a,d[c]),e);c+=2);return e}if(c.keys){d=c.keys();var f=null;if(d.next){for(f=d.next();!f.done;){e=z.h.writer.Ra(a,f.value);if(!e)break;f=d.next()}return e}}if(c.forEach)return c.forEach(function(h,k){e=e&&z.h.writer.Ra(a,k)}),e;throw Error("Cannot walk keys of object type "+z.a.constructor(c).name);};
z.h.writer.Qb=function(a){if(a.constructor.transit$isObject)return!0;var c=a.constructor.toString();c=c.substr(9);c=c.substr(0,c.indexOf("("));c="Object"==c;"undefined"!=typeof Object.defineProperty?Object.defineProperty(a.constructor,"transit$isObject",{value:c,enumerable:!1}):a.constructor.transit$isObject=c;return c};
z.h.writer.Hb=function(a,c,d){var e=null,f=null,h=null;e=null;var k=0;if(c.constructor===Object||null!=c.forEach||a.la&&z.h.writer.Qb(c)){if(a.oa){if(null!=c.forEach){if(z.h.writer.stringableKeys(a,c)){var l={};c.forEach(function(q,r){l[z.h.writer.I(a,r,!0,!1)]=z.h.writer.I(a,q,!1,d)});return l}e=a.La(c);f=[];h=X(z.D.aa,"cmap","",!0,d);if(e)for(;k<e.length;k+=2)f.push(z.h.writer.I(a,e[k],!1,!1)),f.push(z.h.writer.I(a,e[k+1],!1,d));else c.forEach(function(q,r){f.push(z.h.writer.I(a,r,!1,!1));f.push(z.h.writer.I(a,
q,!1,d))});l={};l[h]=f;return l}e=z.o.W(c);for(l={};k<e.length;k++)l[z.h.writer.I(a,e[k],!0,!1)]=z.h.writer.I(a,c[e[k]],!1,d);return l}if(null!=c.forEach){if(z.h.writer.stringableKeys(a,c)){e=a.La(c);l=["^ "];if(e)for(;k<e.length;k+=2)l.push(z.h.writer.I(a,e[k],!0,d)),l.push(z.h.writer.I(a,e[k+1],!1,d));else c.forEach(function(q,r){l.push(z.h.writer.I(a,r,!0,d));l.push(z.h.writer.I(a,q,!1,d))});return l}e=a.La(c);f=[];h=X(z.D.aa,"cmap","",!0,d);if(e)for(;k<e.length;k+=2)f.push(z.h.writer.I(a,e[k],
!1,d)),f.push(z.h.writer.I(a,e[k+1],!1,d));else c.forEach(function(q,r){f.push(z.h.writer.I(a,r,!1,d));f.push(z.h.writer.I(a,q,!1,d))});return[h,f]}l=["^ "];for(e=z.o.W(c);k<e.length;k++)l.push(z.h.writer.I(a,e[k],!0,d)),l.push(z.h.writer.I(a,c[e[k]],!1,d));return l}if(null!=a.mb)return a.mb(c,function(q){return z.h.writer.I(a,q,!0,d)},function(q){return z.h.writer.I(a,q,!1,d)});k=z.a.constructor(c).name;e=Error("Cannot write "+k);e.data={Ta:c,type:k};throw e;};
z.h.writer.Jb=function(a,c,d,e){if(a.oa){var f={};f[X(z.D.aa,c,"",!0,e)]=z.h.writer.I(a,d,!1,e);return f}return[X(z.D.aa,c,"",!0,e),z.h.writer.I(a,d,!1,e)]};z.h.writer.Gb=function(a,c,d,e,f,h,k){if(1===d.length){if("string"===typeof e)return X(z.D.O,d,e,h,k);if(h||a.Ja){(e=a.oa&&c.gb())?(d=e.tag(f),e=e.L(f,e)):e=c.L(f,c);if(null!==e)return X(z.D.O,d,e,h,k);c=Error('Tag "'+d+'" cannot be encoded as string');c.data={tag:d,rep:e,Ta:f};throw c;}}return z.h.writer.Jb(a,d,e,k)};
z.h.writer.I=function(a,c,d,e){null!==a.transform&&(c=a.transform(c));var f=W(a,c)||(a.la?a.la(c,a.a):null),h=f?f.tag(c):null,k=f?f.rep(c):null;if(null!=f&&null!=h)switch(h){case "_":return d?X(z.D.O,"_","",d,e):null;case "s":return X("","",z.h.writer.escape(k),d,e);case "?":return d?X(z.D.O,"?",k.toString()[0],d,e):k;case "i":return Infinity===k?X(z.D.O,"z","INF",d,e):-Infinity===k?X(z.D.O,"z","-INF",d,e):isNaN(k)?X(z.D.O,"z","NaN",d,e):d||"string"===typeof k||k instanceof A?X(z.D.O,"i",k.toString(),
d,e):k;case "d":return d?X(k.O,"d",k,d,e):k;case "b":return X(z.D.O,"b",k,d,e);case "'":return a.oa?(c={},d=X(z.D.aa,"'","",!0,e),c[d]=z.h.writer.I(a,k,!1,e),a=c):a=[X(z.D.aa,"'","",!0,e),z.h.writer.I(a,k,!1,e)],a;case "array":return z.h.writer.Fb(a,k,e);case "map":return z.h.writer.Hb(a,k,e);default:return z.h.writer.Gb(a,f,h,k,c,d,e)}else throw a=z.a.constructor(c).name,e=Error("Cannot write "+a),e.data={Ta:c,type:a},e;};
z.h.writer.Tb=function(a,c){a=W(a,c)||(a.la?a.la(c,a.a):null);if(null!=a)return 1===a.tag(c).length?z.types.quoted(c):c;a=z.a.constructor(c).name;var d=Error("Cannot write "+a);d.data={Ta:c,type:a};throw d;};z.h.writer.Sb=function(a,c,d,e){return JSON.stringify(z.h.writer.I(a,z.h.writer.Tb(a,c),d,e))};z.h.writer.V=function(a,c){this.g=a;this.l=c||{};!1===this.l.cache?this.cache=null:this.cache=this.l.cache?this.l.cache:new z.v.Ia};z.h.writer.V.prototype.M=function(){return this.g};
z.h.writer.V.prototype.marshaller=z.h.writer.V.prototype.M;z.h.writer.V.prototype.write=function(a,c){c=c||{};var d=c.asMapKey||!1,e=this.g.oa?!1:this.cache;a=!1===c.marshalTop?z.h.writer.I(this.g,a,d,e):z.h.writer.Sb(this.g,a,d,e);null!=this.cache&&this.cache.clear();return a};z.h.writer.V.prototype.write=z.h.writer.V.prototype.write;z.h.writer.V.prototype.register=function(a,c){this.g.a.set(a,c)};z.h.writer.V.prototype.register=z.h.writer.V.prototype.register;z.reader=function(a,c){if("json"===a||"json-verbose"===a||null==a)return a=new z.h.reader.tb(c),new z.h.reader.xa(a,c);throw Error("Cannot create reader of type "+a);};z.writer=function(a,c){if("json"===a||"json-verbose"===a||null==a)return"json-verbose"===a&&(null==c&&(c={}),c.verbose=!0),a=new z.h.writer.sb(c),new z.h.writer.V(a,c);c=Error('Type must be "json"');c.data={type:a};throw c;};
z.makeWriteHandler=function(a){function c(){}c.prototype.tag=a.tag;c.prototype.rep=a.rep;c.prototype.L=a.stringRep;c.prototype.gb=a.getVerboseHandler;return new c};z.makeBuilder=function(a){function c(){}c.prototype.init=a.init;c.prototype.add=a.add;c.prototype.finalize=a.finalize;c.prototype.fromArray=a.fromArray;return new c};z.date=z.types.date;z.integer=z.types.jb;z.isInteger=z.types.isInteger;z.uuid=z.types.uuid;z.isUUID=z.types.isUUID;z.bigInt=z.types.cb;z.isBigInt=z.types.Ob;z.bigDec=z.types.bb;
z.isBigDec=z.types.Nb;z.keyword=z.types.keyword;z.isKeyword=z.types.isKeyword;z.symbol=z.types.symbol;z.isSymbol=z.types.isSymbol;z.binary=z.types.binary;z.isBinary=z.types.isBinary;z.uri=z.types.uri;z.isURI=z.types.isURI;z.map=z.types.map;z.isMap=z.types.isMap;z.set=z.types.set;z.isSet=z.types.isSet;z.list=z.types.list;z.isList=z.types.isList;z.quoted=z.types.quoted;z.isQuoted=z.types.isQuoted;z.tagged=z.types.T;z.isTaggedValue=z.types.isTaggedValue;z.link=z.types.link;z.isLink=z.types.isLink;
z.hash=z.j.s;z.hashMapLike=z.j.hashMapLike;z.hashArrayLike=z.j.hashArrayLike;z.equals=z.j.equals;z.extendToEQ=z.j.extendToEQ;z.mapToObject=function(a){var c={};a.forEach(function(d,e){if("string"!==typeof e)throw Error("Cannot convert map with non-string keys");c[e]=d});return c};z.objectToMap=function(a){var c=z.map(),d;for(d in a)a.hasOwnProperty(d)&&c.set(d,a[d]);return c};z.decoder=z.h.decoder.decoder;z.readCache=z.v.readCache;z.writeCache=z.v.writeCache;z.UUIDfromString=z.types.UUIDfromString;
z.randomUUID=z.o.randomUUID;z.stringableKeys=z.h.writer.stringableKeys;z.Yb={};define("transit",[],function(){return z});})();
