// transit-js 0.8.783
// http://transit-format.org
// 
// Copyright 2014 Cognitect. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License..
;(function(){var aa=this;
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function k(a,b){var c=a.split("."),d=aa;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d[e]?d=d[e]:d=d[e]={}:d[e]=b};function l(a,b){this.l=a|0;this.h=b|0}var ca={};function m(a){if(-128<=a&&128>a){var b=ca[a];if(b)return b}b=new l(a|0,0>a?-1:0);-128<=a&&128>a&&(ca[a]=b);return b}function n(a){return isNaN(a)||!isFinite(a)?p:a<=-da?q:a+1>=da?ea:0>a?r(n(-a)):new l(a%t|0,a/t|0)}function v(a,b){return new l(a,b)}
function fa(a,b){if(0==a.length)throw Error("number format error: empty string");var c=b||10;if(2>c||36<c)throw Error("radix out of range: "+c);if("-"==a.charAt(0))return r(fa(a.substring(1),c));if(0<=a.indexOf("-"))throw Error('number format error: interior "-" character: '+a);for(var d=n(Math.pow(c,8)),e=p,f=0;f<a.length;f+=8){var g=Math.min(8,a.length-f),h=parseInt(a.substring(f,f+g),c);8>g?(g=n(Math.pow(c,g)),e=w(e,g).add(n(h))):(e=w(e,d),e=e.add(n(h)))}return e}
var t=4294967296,da=t*t/2,p=m(0),x=m(1),ha=m(-1),ea=v(-1,2147483647),q=v(0,-2147483648),ia=m(16777216);function y(a){return a.h*t+(0<=a.l?a.l:t+a.l)}
l.prototype.toString=function(a){a=a||10;if(2>a||36<a)throw Error("radix out of range: "+a);if(z(this))return"0";if(0>this.h){if(A(this,q)){var b=n(a),c=B(this,b),b=ja(w(c,b),this);return c.toString(a)+b.l.toString(a)}return"-"+r(this).toString(a)}for(var c=n(Math.pow(a,6)),b=this,d="";;){var e=B(b,c),f=ja(b,w(e,c)).l.toString(a),b=e;if(z(b))return f+d;for(;6>f.length;)f="0"+f;d=""+f+d}};function z(a){return 0==a.h&&0==a.l}function A(a,b){return a.h==b.h&&a.l==b.l}
function C(a,b){if(A(a,b))return 0;var c=0>a.h,d=0>b.h;return c&&!d?-1:!c&&d?1:0>ja(a,b).h?-1:1}function r(a){return A(a,q)?q:v(~a.l,~a.h).add(x)}l.prototype.add=function(a){var b=this.h>>>16,c=this.h&65535,d=this.l>>>16,e=a.h>>>16,f=a.h&65535,g=a.l>>>16,h;h=0+((this.l&65535)+(a.l&65535));a=0+(h>>>16);a+=d+g;d=0+(a>>>16);d+=c+f;c=0+(d>>>16);c=c+(b+e)&65535;return v((a&65535)<<16|h&65535,c<<16|d&65535)};function ja(a,b){return a.add(r(b))}
function w(a,b){if(z(a)||z(b))return p;if(A(a,q))return 1==(b.l&1)?q:p;if(A(b,q))return 1==(a.l&1)?q:p;if(0>a.h)return 0>b.h?w(r(a),r(b)):r(w(r(a),b));if(0>b.h)return r(w(a,r(b)));if(0>C(a,ia)&&0>C(b,ia))return n(y(a)*y(b));var c=a.h>>>16,d=a.h&65535,e=a.l>>>16,f=a.l&65535,g=b.h>>>16,h=b.h&65535,Ba=b.l>>>16,ga=b.l&65535,M,u,H,Ca;Ca=0+f*ga;H=0+(Ca>>>16);H+=e*ga;u=0+(H>>>16);H=(H&65535)+f*Ba;u+=H>>>16;H&=65535;u+=d*ga;M=0+(u>>>16);u=(u&65535)+e*Ba;M+=u>>>16;u&=65535;u+=f*h;M+=u>>>16;u&=65535;M=M+(c*
ga+d*Ba+e*h+f*g)&65535;return v(H<<16|Ca&65535,M<<16|u)}
function B(a,b){if(z(b))throw Error("division by zero");if(z(a))return p;if(A(a,q)){if(A(b,x)||A(b,ha))return q;if(A(b,q))return x;var c;c=1;if(0==c)c=a;else{var d=a.h;c=32>c?v(a.l>>>c|d<<32-c,d>>c):v(d>>c-32,0<=d?0:-1)}c=ka(B(c,b),1);if(A(c,p))return 0>b.h?x:ha;d=ja(a,w(b,c));return c.add(B(d,b))}if(A(b,q))return p;if(0>a.h)return 0>b.h?B(r(a),r(b)):r(B(r(a),b));if(0>b.h)return r(B(a,r(b)));for(var e=p,d=a;0<=C(d,b);){c=Math.max(1,Math.floor(y(d)/y(b)));for(var f=Math.ceil(Math.log(c)/Math.LN2),
f=48>=f?1:Math.pow(2,f-48),g=n(c),h=w(g,b);0>h.h||0<C(h,d);)c-=f,g=n(c),h=w(g,b);z(g)&&(g=x);e=e.add(g);d=ja(d,h)}return e}function ka(a,b){b&=63;if(0==b)return a;var c=a.l;return 32>b?v(c<<b,a.h<<b|c>>>32-b):v(0,c<<b-32)}function la(a,b){b&=63;if(0==b)return a;var c=a.h;return 32>b?v(a.l>>>b|c<<32-b,c>>>b):32==b?v(c,0):v(c>>>b-32,0)};function ma(a,b){if(3<a.length){if(b)return!0;var c=a.charAt(1);return"~"===a.charAt(0)?":"===c||"$"===c||"#"===c:!1}return!1}function na(a){var b=Math.floor(a/44);a=String.fromCharCode(a%44+48);return 0===b?"^"+a:"^"+String.fromCharCode(b+48)+a}function oa(){this.a=this.k=0;this.e={}}oa.prototype.write=function(a,b){if(ma(a,b)){1936===this.k&&this.clear();var c=this.e[a];return null==c?(this.e[a]=[na(this.k),this.a],this.k++,a):c[1]!=this.a?(c[1]=this.a,c[0]=na(this.k),this.k++,a):c[0]}return a};
oa.prototype.clear=function(){this.k=0;this.a++};function pa(){this.k=0;this.a=[]}pa.prototype.write=function(a){1936==this.k&&(this.k=0);this.a[this.k]=a;this.k++;return a};pa.prototype.L=function(a){return this.a[2===a.length?a.charCodeAt(1)-48:44*(a.charCodeAt(1)-48)+(a.charCodeAt(2)-48)]};pa.prototype.clear=function(){this.k=0};var D="undefined"!=typeof Object.keys?function(a){return Object.keys(a)}:function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},E="undefined"!=typeof Array.isArray?function(a){return Array.isArray(a)}:function(a){return"array"===ba(a)};function F(){return Math.round(15*Math.random()).toString(16)};var qa=1;function G(a,b){if(null==a)return null==b;if(a===b)return!0;if("object"===typeof a){if(E(a)){if(E(b)&&a.length===b.length){for(var c=0;c<a.length;c++)if(!G(a[c],b[c]))return!1;return!0}return!1}if(a.s)return a.s(b);if(null!=b&&"object"===typeof b){if(b.s)return b.s(a);var c=0,d=D(b).length,e;for(e in a)if(a.hasOwnProperty(e)&&(c++,!b.hasOwnProperty(e)||!G(a[e],b[e])))return!1;return c===d}}return!1}function ra(a,b){return a^b+2654435769+(a<<6)+(a>>2)}var sa={},ta=0;
function ua(a){var b=0;if(null!=a.forEach)a.forEach(function(a,c){b=(b+(I(c)^I(a)))%4503599627370496});else for(var c=D(a),d=0;d<c.length;d++)var e=c[d],f=a[e],b=(b+(I(e)^I(f)))%4503599627370496;return b}function va(a){var b=0;if(E(a))for(var c=0;c<a.length;c++)b=ra(b,I(a[c]));else a.forEach&&a.forEach(function(a){b=ra(b,I(a))});return b}
function I(a){if(null==a)return 0;switch(typeof a){case "number":return a;case "boolean":return!0===a?1:0;case "string":var b=sa[a];if(null==b){for(var c=b=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;ta++;256<=ta&&(sa={},ta=1);sa[a]=b}a=b;return a;case "function":if(b=a.transit$hashCode$)return b;b=qa;"undefined"!=typeof Object.defineProperty?Object.defineProperty(a,"transit$hashCode$",{value:b,enumerable:!1}):a.transit$hashCode$=b;qa++;return b;default:return a instanceof Date?a.valueOf():
E(a)?va(a):a.v?a.v():ua(a)}};function J(a,b){this.tag=a;this.rep=b;this.a=-1}J.prototype.toString=function(){return"[TaggedValue: "+this.tag+", "+this.rep+"]"};J.prototype.e=function(a){return G(this,a)};J.prototype.equiv=J.prototype.e;J.prototype.s=function(a){return a instanceof J?this.tag===a.tag&&G(this.rep,a.rep):!1};J.prototype.v=function(){-1===this.a&&(this.a=ra(I(this.tag),I(this.rep)));return this.a};function K(a,b){return new J(a,b)}var wa=fa("9007199254740991"),xa=fa("-9007199254740991");
function ya(a){if("number"===typeof a)return a;if(a instanceof l)return a;a=fa(a,10);return 0<C(a,wa)||0>C(a,xa)?a:y(a)}l.prototype.a=function(a){return G(this,a)};l.prototype.equiv=l.prototype.a;l.prototype.s=function(a){return a instanceof l&&A(this,a)};l.prototype.v=function(){return this.l};function za(a){return K("n",a)}function Aa(a){return K("f",a)}function L(a){this.name=a;this.a=-1}L.prototype.toString=function(){return":"+this.name};
L.prototype.namespace=function(){var a=this.name.indexOf("/");return-1!=a?this.name.substring(0,a):null};L.prototype.e=function(a){return G(this,a)};L.prototype.equiv=L.prototype.e;L.prototype.s=function(a){return a instanceof L&&this.name==a.name};L.prototype.v=function(){-1===this.a&&(this.a=I(this.name));return this.a};function Da(a){return new L(a)}function N(a){this.name=a;this.a=-1}N.prototype.namespace=function(){var a=this.name.indexOf("/");return-1!=a?this.name.substring(0,a):null};
N.prototype.toString=function(){return"[Symbol: "+this.name+"]"};N.prototype.e=function(a){return G(this,a)};N.prototype.equiv=N.prototype.e;N.prototype.s=function(a){return a instanceof N&&this.name==a.name};N.prototype.v=function(){-1===this.a&&(this.a=I(this.name));return this.a};function Ea(a){return new N(a)}function Fa(a,b,c){var d="";c=c||b+1;for(var e=8*(7-b),f=ka(m(255),e);b<c;b++,e-=8,f=la(f,8)){var g=la(v(a.l&f.l,a.h&f.h),e).toString(16);1==g.length&&(g="0"+g);d+=g}return d}
function O(a,b){this.e=a;this.q=b;this.a=-1}O.prototype.toString=function(a){var b=this.e,c=this.q;a=""+(Fa(b,0,4)+"-");a+=Fa(b,4,6)+"-";a+=Fa(b,6,8)+"-";a+=Fa(c,0,2)+"-";return a+=Fa(c,2,8)};O.prototype.w=function(a){return G(this,a)};O.prototype.equiv=O.prototype.w;O.prototype.s=function(a){return a instanceof O&&A(this.e,a.e)&&A(this.q,a.q)};O.prototype.v=function(){-1===this.a&&(this.a=I(this.toString()));return this.a};
function Ga(a){a=a.replace(/-/g,"");for(var b=null,c=null,d=c=0,e=24,f=0,f=c=0,e=24;8>f;f+=2,e-=8)c|=parseInt(a.substring(f,f+2),16)<<e;d=0;f=8;for(e=24;16>f;f+=2,e-=8)d|=parseInt(a.substring(f,f+2),16)<<e;b=v(d,c);c=0;f=16;for(e=24;24>f;f+=2,e-=8)c|=parseInt(a.substring(f,f+2),16)<<e;d=0;for(e=f=24;32>f;f+=2,e-=8)d|=parseInt(a.substring(f,f+2),16)<<e;c=v(d,c);return new O(b,c)}function Ha(a){a="number"===typeof a?a:parseInt(a,10);return new Date(a)}
Date.prototype.s=function(a){return a instanceof Date?this.valueOf()===a.valueOf():!1};Date.prototype.v=function(){return this.valueOf()};
function Ia(a,b){var c;if(b&&!1===b.K||"undefined"==typeof Buffer)if("undefined"!=typeof Uint8Array){if("undefined"!=typeof atob)c=atob(a);else{c=String(a).replace(/=+$/,"");if(1==c.length%4)throw Error("'atob' failed: The string to be decoded is not correctly encoded.");for(var d=0,e,f,g=0,h="";f=c.charAt(g++);~f&&(e=d%4?64*e+f:f,d++%4)?h+=String.fromCharCode(255&e>>(-2*d&6)):0)f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(f);c=h}d=c.length;e=new Uint8Array(d);for(f=
0;f<d;f++)e[f]=c.charCodeAt(f);c=e}else c=K("b",a);else c=new Buffer(a,"base64");return c}function Ja(a){return K("r",a)}function P(a,b){this.entries=a;this.type=b||0;this.k=0}P.prototype.next=function(){if(this.k<this.entries.length){var a=null;0===this.type?a=this.entries[this.k]:1===this.type?a=this.entries[this.k+1]:a=[this.entries[this.k],this.entries[this.k+1]];a={value:a,done:!1};this.k+=2;return a}return{value:null,done:!0}};P.prototype.next=P.prototype.next;
function Q(a,b){this.map=a;this.type=b||0;this.keys=Ka(this.map);this.k=0;this.e=null;this.a=0}Q.prototype.next=function(){if(this.k<this.map.size){null!=this.e&&this.a<this.e.length||(this.e=this.map.map[this.keys[this.k]],this.a=0);var a=null;0===this.type?a=this.e[this.a]:1===this.type?a=this.e[this.a+1]:a=[this.e[this.a],this.e[this.a+1]];a={value:a,done:!1};this.k++;this.a+=2;return a}return{value:null,done:!0}};Q.prototype.next=Q.prototype.next;
function La(a,b){if(a instanceof R&&Ma(b)){if(a.size!==b.size)return!1;for(var c in a.map)for(var d=a.map[c],e=0;e<d.length;e+=2)if(!G(d[e+1],b.get(d[e])))return!1;return!0}if(a instanceof S&&Ma(b)){if(a.size!==b.size)return!1;c=a.j;for(e=0;e<c.length;e+=2)if(!G(c[e+1],b.get(c[e])))return!1;return!0}if(null!=b&&"object"===typeof b&&(e=D(b),c=e.length,a.size===c)){for(d=0;d<c;d++){var f=e[d];if(!a.has(f)||!G(b[f],a.get(f)))return!1}return!0}return!1}
function S(a){this.j=a;this.g=null;this.a=-1;this.size=a.length/2;this.e=0}S.prototype.toString=function(){return"[TransitArrayMap]"};function Na(a){if(a.g)throw Error("Invalid operation, already converted");if(8>a.size)return!1;a.e++;return 32<a.e?(a.g=T(a.j,!1,!0),a.j=[],!0):!1}S.prototype.clear=function(){this.a=-1;this.g?this.g.clear():this.j=[];this.size=0};S.prototype.clear=S.prototype.clear;S.prototype.keys=function(){return this.g?this.g.keys():new P(this.j,0)};S.prototype.keys=S.prototype.keys;
S.prototype.B=function(){if(this.g)return this.g.B();for(var a=[],b=0,c=0;c<this.j.length;b++,c+=2)a[b]=this.j[c];return a};S.prototype.keySet=S.prototype.B;S.prototype.entries=function(){return this.g?this.g.entries():new P(this.j,2)};S.prototype.entries=S.prototype.entries;S.prototype.values=function(){return this.g?this.g.values():new P(this.j,1)};S.prototype.values=S.prototype.values;
S.prototype.forEach=function(a){if(this.g)this.g.forEach(a);else for(var b=0;b<this.j.length;b+=2)a(this.j[b+1],this.j[b])};S.prototype.forEach=S.prototype.forEach;S.prototype.get=function(a,b){if(this.g)return this.g.get(a);if(Na(this))return this.get(a);for(var c=0;c<this.j.length;c+=2)if(G(this.j[c],a))return this.j[c+1];return b};S.prototype.get=S.prototype.get;
S.prototype.has=function(a){if(this.g)return this.g.has(a);if(Na(this))return this.has(a);for(var b=0;b<this.j.length;b+=2)if(G(this.j[b],a))return!0;return!1};S.prototype.has=S.prototype.has;S.prototype.set=function(a,b){this.a=-1;if(this.g)this.g.set(a,b),this.size=this.g.size;else{for(var c=0;c<this.j.length;c+=2)if(G(this.j[c],a)){this.j[c+1]=b;return}this.j.push(a);this.j.push(b);this.size++;32<this.size&&(this.g=T(this.j,!1,!0),this.j=null)}};S.prototype.set=S.prototype.set;
S.prototype["delete"]=function(a){this.a=-1;if(this.g)return a=this.g["delete"](a),this.size=this.g.size,a;for(var b=0;b<this.j.length;b+=2)if(G(this.j[b],a))return a=this.j[b+1],this.j.splice(b,2),this.size--,a};S.prototype.clone=function(){var a=T();this.forEach(function(b,c){a.set(c,b)});return a};S.prototype.clone=S.prototype.clone;S.prototype.v=function(){if(this.g)return this.g.v();-1===this.a&&(this.a=ua(this));return this.a};S.prototype.s=function(a){return this.g?La(this.g,a):La(this,a)};
function R(a,b,c){this.map=b||{};this.a=a||[];this.size=c||0;this.e=-1}R.prototype.toString=function(){return"[TransitMap]"};R.prototype.clear=function(){this.e=-1;this.map={};this.a=[];this.size=0};R.prototype.clear=R.prototype.clear;function Ka(a){return null!=a.a?a.a:D(a.map)}R.prototype["delete"]=function(a){this.e=-1;this.a=null;for(var b=I(a),c=this.map[b],d=0;d<c.length;d+=2)if(G(a,c[d]))return a=c[d+1],c.splice(d,2),0===c.length&&delete this.map[b],this.size--,a};
R.prototype.entries=function(){return new Q(this,2)};R.prototype.entries=R.prototype.entries;R.prototype.forEach=function(a){for(var b=Ka(this),c=0;c<b.length;c++)for(var d=this.map[b[c]],e=0;e<d.length;e+=2)a(d[e+1],d[e],this)};R.prototype.forEach=R.prototype.forEach;R.prototype.get=function(a,b){var c=I(a),c=this.map[c];if(null!=c)for(var d=0;d<c.length;d+=2){if(G(a,c[d]))return c[d+1]}else return b};R.prototype.get=R.prototype.get;
R.prototype.has=function(a){var b=I(a),b=this.map[b];if(null!=b)for(var c=0;c<b.length;c+=2)if(G(a,b[c]))return!0;return!1};R.prototype.has=R.prototype.has;R.prototype.keys=function(){return new Q(this,0)};R.prototype.keys=R.prototype.keys;R.prototype.B=function(){for(var a=Ka(this),b=[],c=0;c<a.length;c++)for(var d=this.map[a[c]],e=0;e<d.length;e+=2)b.push(d[e]);return b};R.prototype.keySet=R.prototype.B;
R.prototype.set=function(a,b){this.e=-1;var c=I(a),d=this.map[c];if(null==d)this.a&&this.a.push(c),this.map[c]=[a,b],this.size++;else{for(var c=!0,e=0;e<d.length;e+=2)if(G(b,d[e])){c=!1;d[e]=b;break}c&&(d.push(a),d.push(b),this.size++)}};R.prototype.set=R.prototype.set;R.prototype.values=function(){return new Q(this,1)};R.prototype.values=R.prototype.values;R.prototype.clone=function(){var a=T();this.forEach(function(b,c){a.set(c,b)});return a};R.prototype.clone=R.prototype.clone;
R.prototype.v=function(){-1===this.e&&(this.e=ua(this));return this.e};R.prototype.s=function(a){return La(this,a)};
function T(a,b,c){a=a||[];b=!1===b?b:!0;if((!0!==c||!c)&&64>=a.length){if(b){var d=a;a=[];for(b=0;b<d.length;b+=2){var e=!1;for(c=0;c<a.length;c+=2)if(G(a[c],d[b])){a[c+1]=d[b+1];e=!0;break}e||(a.push(d[b]),a.push(d[b+1]))}}return new S(a)}var d={},e=[],f=0;for(b=0;b<a.length;b+=2){c=I(a[b]);var g=d[c];if(null==g)e.push(c),d[c]=[a[b],a[b+1]],f++;else{var h=!0;for(c=0;c<g.length;c+=2)if(G(g[c],a[b])){g[c+1]=a[b+1];h=!1;break}h&&(g.push(a[b]),g.push(a[b+1]),f++)}}return new R(e,d,f)}
function Ma(a){return a instanceof S||a instanceof R}function U(a){this.map=a;this.size=a.size}U.prototype.toString=function(){return"[TransitSet]"};U.prototype.add=function(a){this.map.set(a,a);this.size=this.map.size};U.prototype.add=U.prototype.add;U.prototype.clear=function(){this.map=new R;this.size=0};U.prototype.clear=U.prototype.clear;U.prototype["delete"]=function(a){a=this.map["delete"](a);this.size=this.map.size;return a};U.prototype.entries=function(){return this.map.entries()};
U.prototype.entries=U.prototype.entries;U.prototype.forEach=function(a){var b=this;this.map.forEach(function(c,d){a(d,b)})};U.prototype.forEach=U.prototype.forEach;U.prototype.has=function(a){return this.map.has(a)};U.prototype.has=U.prototype.has;U.prototype.keys=function(){return this.map.keys()};U.prototype.keys=U.prototype.keys;U.prototype.B=function(){return this.map.B()};U.prototype.keySet=U.prototype.B;U.prototype.values=function(){return this.map.values()};U.prototype.values=U.prototype.values;
U.prototype.clone=function(){var a=Oa();this.forEach(function(b){a.add(b)});return a};U.prototype.clone=U.prototype.clone;U.prototype.s=function(a){if(a instanceof U){if(this.size===a.size)return G(this.map,a.map)}else return!1};U.prototype.v=function(){return I(this.map)};
function Oa(a){a=a||[];for(var b={},c=[],d=0,e=0;e<a.length;e++){var f=I(a[e]),g=b[f];if(null==g)c.push(f),b[f]=[a[e],a[e]],d++;else{for(var f=!0,h=0;h<g.length;h+=2)if(G(g[h],a[e])){f=!1;break}f&&(g.push(a[e]),g.push(a[e]),d++)}}return new U(new R(c,b,d))}function Pa(a){return K("'",a)}function Qa(a){return K("list",a)}function Ra(a){return K("link",a)};var Sa=0,Ta=(8|3&Math.round(14*Math.random())).toString(16),Ua="transit$guid$"+(F()+F()+F()+F()+F()+F()+F()+F()+"-"+F()+F()+F()+F()+"-4"+F()+F()+F()+"-"+Ta+F()+F()+F()+"-"+F()+F()+F()+F()+F()+F()+F()+F()+F()+F()+F()+F());
function Va(a){if(null==a)return"null";if(a===String)return"string";if(a===Boolean)return"boolean";if(a===Number)return"number";if(a===Array)return"array";if(a===Object)return"map";var b=a[Ua];null==b&&("undefined"!=typeof Object.defineProperty?(b=++Sa,Object.defineProperty(a,Ua,{value:b,enumerable:!1})):a[Ua]=b=++Sa);return b}function V(a,b){for(var c=a.toString(),d=c.length;d<b;d++)c="0"+c;return c}function Wa(){}Wa.prototype.tag=function(){return"_"};Wa.prototype.rep=function(){return null};
Wa.prototype.p=function(){return"null"};function Xa(){}Xa.prototype.tag=function(){return"s"};Xa.prototype.rep=function(a){return a};Xa.prototype.p=function(a){return a};function Ya(){}Ya.prototype.tag=function(){return"i"};Ya.prototype.rep=function(a){return a};Ya.prototype.p=function(a){return a.toString()};function Za(){}Za.prototype.tag=function(){return"i"};Za.prototype.rep=function(a){return a.toString()};Za.prototype.p=function(a){return a.toString()};function $a(){}$a.prototype.tag=function(){return"?"};
$a.prototype.rep=function(a){return a};$a.prototype.p=function(a){return a.toString()};function ab(){}ab.prototype.tag=function(){return"array"};ab.prototype.rep=function(a){return a};ab.prototype.p=function(){return null};function bb(){}bb.prototype.tag=function(){return"map"};bb.prototype.rep=function(a){return a};bb.prototype.p=function(){return null};function cb(){}cb.prototype.tag=function(){return"t"};
cb.prototype.rep=function(a){return a.getUTCFullYear()+"-"+V(a.getUTCMonth()+1,2)+"-"+V(a.getUTCDate(),2)+"T"+V(a.getUTCHours(),2)+":"+V(a.getUTCMinutes(),2)+":"+V(a.getUTCSeconds(),2)+"."+V(a.getUTCMilliseconds(),3)+"Z"};cb.prototype.p=function(a,b){return b.rep(a)};function db(){}db.prototype.tag=function(){return"m"};db.prototype.rep=function(a){return a.valueOf()};db.prototype.p=function(a){return a.valueOf().toString()};db.prototype.M=function(){return new cb};function eb(){}
eb.prototype.tag=function(){return"u"};eb.prototype.rep=function(a){return a.toString()};eb.prototype.p=function(a){return a.toString()};function fb(){}fb.prototype.tag=function(){return":"};fb.prototype.rep=function(a){return a.name};fb.prototype.p=function(a,b){return b.rep(a)};function gb(){}gb.prototype.tag=function(){return"$"};gb.prototype.rep=function(a){return a.name};gb.prototype.p=function(a,b){return b.rep(a)};function hb(){}hb.prototype.tag=function(a){return a.tag};hb.prototype.rep=function(a){return a.rep};
hb.prototype.p=function(){return null};function ib(){}ib.prototype.tag=function(){return"set"};ib.prototype.rep=function(a){var b=[];a.forEach(function(a){b.push(a)});return K("array",b)};ib.prototype.p=function(){return null};function jb(){}jb.prototype.tag=function(){return"map"};jb.prototype.rep=function(a){return a};jb.prototype.p=function(){return null};function kb(){}kb.prototype.tag=function(){return"map"};kb.prototype.rep=function(a){return a};kb.prototype.p=function(){return null};
function lb(){}lb.prototype.tag=function(){return"b"};lb.prototype.rep=function(a){return a.toString("base64")};lb.prototype.p=function(){return null};function mb(){}mb.prototype.tag=function(){return"b"};
mb.prototype.rep=function(a){for(var b=0,c=a.length,d="",e=null;b<c;)e=a.subarray(b,Math.min(b+32768,c)),d+=String.fromCharCode.apply(null,e),b+=32768;var f;if("undefined"!=typeof btoa)f=btoa(d);else{a=String(d);c=0;d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";for(e="";a.charAt(c|0)||(d="=",c%1);e+=d.charAt(63&f>>8-c%1*8)){b=a.charCodeAt(c+=.75);if(255<b)throw Error("'btoa' failed: The string to be encoded contains characters outside of the Latin1 range.");f=f<<8|b}f=e}return f};
mb.prototype.p=function(){return null};function nb(){this.o={};this.set(null,new Wa);this.set(String,new Xa);this.set(Number,new Ya);this.set(l,new Za);this.set(Boolean,new $a);this.set(Array,new ab);this.set(Object,new bb);this.set(Date,new db);this.set(O,new eb);this.set(L,new fb);this.set(N,new gb);this.set(J,new hb);this.set(U,new ib);this.set(S,new jb);this.set(R,new kb);"undefined"!=typeof Buffer&&this.set(Buffer,new lb);"undefined"!=typeof Uint8Array&&this.set(Uint8Array,new mb)}
nb.prototype.get=function(a){var b=null,b="string"===typeof a?this.o[a]:this.o[Va(a)];return null!=b?b:this.o["default"]};nb.prototype.get=nb.prototype.get;nb.prototype.set=function(a,b){var c;if(c="string"===typeof a)a:{switch(a){case "null":case "string":case "boolean":case "number":case "array":case "map":c=!1;break a}c=!0}c?this.o[a]=b:this.o[Va(a)]=b};function ob(a){this.G=a}
function W(a){this.q=a||{};this.o={};for(var b in this.A.o)this.o[b]=this.A.o[b];for(b in this.q.handlers){a:{switch(b){case "_":case "s":case "?":case "i":case "d":case "b":case "'":case "array":case "map":a=!0;break a}a=!1}if(a)throw Error('Cannot override handler for ground type "'+b+'"');this.o[b]=this.q.handlers[b]}this.F=null!=this.q.preferStrings?this.q.preferStrings:this.A.F;this.K=null!=this.q.preferBuffers?this.q.preferBuffers:this.A.K;this.I=this.q.defaultHandler||this.A.I;this.e=this.q.mapBuilder;
this.w=this.q.arrayBuilder}
W.prototype.A={o:{_:function(){return null},"?":function(a){return"t"===a},b:function(a,b){return Ia(a,b)},i:function(a){return ya(a)},n:function(a){return za(a)},d:function(a){return parseFloat(a)},f:function(a){return Aa(a)},c:function(a){return a},":":function(a){return Da(a)},$:function(a){return Ea(a)},r:function(a){return Ja(a)},z:function(a){a:switch(a){case "-INF":a=-Infinity;break a;case "INF":a=Infinity;break a;case "NaN":a=NaN;break a;default:throw Error("Invalid special double value "+a);
}return a},"'":function(a){return a},m:function(a){return Ha(a)},t:function(a){return new Date(a)},u:function(a){return Ga(a)},set:function(a){return Oa(a)},list:function(a){return Qa(a)},link:function(a){return Ra(a)},cmap:function(a){return T(a,!1)}},I:function(a,b){return K(a,b)},F:!0,K:!0};
W.prototype.a=function(a,b,c,d){if(null==a)return null;switch(typeof a){case "string":return ma(a,c)?(a=pb(this,a),b&&b.write(a,c),b=a):b="^"===a.charAt(0)&&" "!==a.charAt(1)?b.L(a,c):pb(this,a),b;case "object":if(E(a))if("^ "===a[0])if(this.e)if(17>a.length&&this.e.fromArray){d=[];for(c=1;c<a.length;c+=2)d.push(this.a(a[c],b,!0,!1)),d.push(this.a(a[c+1],b,!1,!1));b=this.e.fromArray(d,a)}else{d=this.e.init(a);for(c=1;c<a.length;c+=2)d=this.e.add(d,this.a(a[c],b,!0,!1),this.a(a[c+1],b,!1,!1),a);b=
this.e.finalize(d,a)}else{d=[];for(c=1;c<a.length;c+=2)d.push(this.a(a[c],b,!0,!1)),d.push(this.a(a[c+1],b,!1,!1));b=T(d,!1)}else b=qb(this,a,b,c,d);else{c=D(a);var e=c[0];if((d=1==c.length?this.a(e,b,!1,!1):null)&&d instanceof ob)a=a[e],c=this.o[d.G],b=null!=c?c(this.a(a,b,!1,!0),this):K(d.G,this.a(a,b,!1,!1));else if(this.e)if(16>c.length&&this.e.fromArray){var f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.a(e,b,!0,!1)),f.push(this.a(a[e],b,!1,!1));b=this.e.fromArray(f,a)}else{f=this.e.init(a);
for(d=0;d<c.length;d++)e=c[d],f=this.e.add(f,this.a(e,b,!0,!1),this.a(a[e],b,!1,!1),a);b=this.e.finalize(f,a)}else{f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.a(e,b,!0,!1)),f.push(this.a(a[e],b,!1,!1));b=T(f,!1)}}return b}return a};W.prototype.decode=W.prototype.a;
function qb(a,b,c,d,e){if(e){var f=[];for(e=0;e<b.length;e++)f.push(a.a(b[e],c,d,!1));return f}f=c&&c.k;if(2===b.length&&"string"===typeof b[0]&&(e=a.a(b[0],c,!1,!1))&&e instanceof ob)return b=b[1],f=a.o[e.G],null!=f?f=f(a.a(b,c,d,!0),a):K(e.G,a.a(b,c,d,!1));c&&f!=c.k&&(c.k=f);if(a.w){if(32>=b.length&&a.w.fromArray){f=[];for(e=0;e<b.length;e++)f.push(a.a(b[e],c,d,!1));return a.w.fromArray(f,b)}f=a.w.init(b);for(e=0;e<b.length;e++)f=a.w.add(f,a.a(b[e],c,d,!1),b);return a.w.finalize(f,b)}f=[];for(e=
0;e<b.length;e++)f.push(a.a(b[e],c,d,!1));return f}function pb(a,b){if("~"===b.charAt(0)){var c=b.charAt(1);if("~"===c||"^"===c||"`"===c)return b.substring(1);if("#"===c)return new ob(b.substring(2));var d=a.o[c];return null==d?a.I(c,b.substring(2)):d(b.substring(2),a)}return b};function rb(a){this.a=new W(a)}function sb(a,b){this.q=a;this.e=b||{};this.a=this.e.cache?this.e.cache:new pa}sb.prototype.L=function(a){var b=this.a;a=this.q.a.a(JSON.parse(a),b);this.a.clear();return a};sb.prototype.read=sb.prototype.L;function tb(a){this.a=a||{};this.F=null!=this.a.preferStrings?this.a.preferStrings:!0;this.N=this.a.objectBuilder||null;this.o=new nb;if(a=this.a.handlers){if(E(a)||!a.forEach)throw Error('transit writer "handlers" option must be a map');var b=this;a.forEach(function(a,d){if(void 0!==d)b.o.set(d,a);else throw Error("Cannot create handler for JavaScript undefined");})}this.C=this.a.handlerForForeign;this.H=this.a.unpack||function(a){return a instanceof S&&null===a.g?a.j:!1};this.D=this.a&&this.a.verbose||
!1}function ub(a,b){var c=a.o.get(null==b?null:b.constructor);return null!=c?c:(c=b&&b.transitTag)?a.o.get(c):null}function X(a,b,c,d,e){a=a+b+c;return e?e.write(a,d):a}function vb(a,b,c){var d=[];if(E(b))for(var e=0;e<b.length;e++)d.push(Y(a,b[e],!1,c));else b.forEach(function(b){d.push(Y(a,b,!1,c))});return d}function wb(a,b){if("string"!==typeof b){var c=ub(a,b);return c&&1===c.tag(b).length}return!0}
function xb(a,b){var c=a.H(b),d=!0;if(c){for(var e=0;e<c.length&&(d=wb(a,c[e]),d);e+=2);return d}if(b.keys&&(c=b.keys(),e=null,c.next)){for(e=c.next();!e.done;){d=wb(a,e.value);if(!d)break;e=c.next()}return d}if(b.forEach)return b.forEach(function(b,c){d=d&&wb(a,c)}),d;throw Error("Cannot walk keys of object type "+(null==b?null:b.constructor).name);}
function yb(a){if(a.constructor.transit$isObject)return!0;var b=a.constructor.toString(),b=b.substr(9),b=b.substr(0,b.indexOf("(")),b="Object"==b;"undefined"!=typeof Object.defineProperty?Object.defineProperty(a.constructor,"transit$isObject",{value:b,enumerable:!1}):a.constructor.transit$isObject=b;return b}
function zb(a,b,c){if(b.constructor===Object||null!=b.forEach||a.C&&yb(b)){if(a.D){if(null!=b.forEach){if(xb(a,b)){var d={};b.forEach(function(b,e){d[Y(a,e,!0,!1)]=Y(a,b,!1,c)});return d}var e=a.H(b),f=[],g=X("~#","cmap","",!0,c);if(e)for(var h=0;h<e.length;h+=2)f.push(Y(a,e[h],!0,!1)),f.push(Y(a,e[h+1],!1,c));else b.forEach(function(b,d){f.push(Y(a,d,!0,!1));f.push(Y(a,b,!1,c))});d={};d[g]=f;return d}d={};e=D(b);for(h=0;h<e.length;h++)d[Y(a,e[h],!0,!1)]=Y(a,b[e[h]],!1,c);return d}if(null!=b.forEach){if(xb(a,
b)){e=a.H(b);d=["^ "];if(e)for(h=0;h<e.length;h+=2)d.push(Y(a,e[h],!0,c)),d.push(Y(a,e[h+1],!1,c));else b.forEach(function(b,e){d.push(Y(a,e,!0,c));d.push(Y(a,b,!1,c))});return d}e=a.H(b);f=[];g=X("~#","cmap","",!0,c);if(e)for(h=0;h<e.length;h+=2)f.push(Y(a,e[h],!0,c)),f.push(Y(a,e[h+1],!1,c));else b.forEach(function(b,d){f.push(Y(a,d,!0,c));f.push(Y(a,b,!1,c))});return[g,f]}d=["^ "];e=D(b);for(h=0;h<e.length;h++)d.push(Y(a,e[h],!0,c)),d.push(Y(a,b[e[h]],!1,c));return d}if(null!=a.N)return a.N(b,
function(b){return Y(a,b,!0,c)},function(b){return Y(a,b,!1,c)});h=(null==b?null:b.constructor).name;e=Error("Cannot write "+h);e.data={J:b,type:h};throw e;}
function Y(a,b,c,d){var e=ub(a,b)||(a.C?a.C(b,a.o):null),f=e?e.tag(b):null,g=e?e.rep(b):null;if(null!=e&&null!=f)switch(f){case "_":return c?X("~","_","",c,d):null;case "s":return 0<g.length?(a=g.charAt(0),a="~"===a||"^"===a||"`"===a?"~"+g:g):a=g,X("","",a,c,d);case "?":return c?X("~","?",g.toString()[0],c,d):g;case "i":return Infinity===g?X("~","z","INF",c,d):-Infinity===g?X("~","z","-INF",c,d):isNaN(g)?X("~","z","NaN",c,d):c||"string"===typeof g||g instanceof l?X("~","i",g.toString(),c,d):g;case "d":return c?
X(g.O,"d",g,c,d):g;case "b":return X("~","b",g,c,d);case "'":return a.D?(b={},c=X("~#","'","",!0,d),b[c]=Y(a,g,!1,d),d=b):d=[X("~#","'","",!0,d),Y(a,g,!1,d)],d;case "array":return vb(a,g,d);case "map":return zb(a,g,d);default:a:{if(1===f.length){if("string"===typeof g){d=X("~",f,g,c,d);break a}if(c||a.F){(a=a.D&&e.M())?(f=a.tag(b),g=a.p(b,a)):g=e.p(b,e);if(null!==g){d=X("~",f,g,c,d);break a}d=Error('Tag "'+f+'" cannot be encoded as string');d.data={tag:f,rep:g,J:b};throw d;}}b=f;c=g;a.D?(g={},g[X("~#",
b,"",!0,d)]=Y(a,c,!1,d),d=g):d=[X("~#",b,"",!0,d),Y(a,c,!1,d)]}return d}else throw d=(null==b?null:b.constructor).name,a=Error("Cannot write "+d),a.data={J:b,type:d},a;}function Ab(a,b){var c=ub(a,b)||(a.C?a.C(b,a.o):null);if(null!=c)return 1===c.tag(b).length?Pa(b):b;var c=(null==b?null:b.constructor).name,d=Error("Cannot write "+c);d.data={J:b,type:c};throw d;}function Z(a,b){this.a=a;this.q=b||{};!1===this.q.cache?this.e=null:this.e=this.q.cache?this.q.cache:new oa}Z.prototype.A=function(){return this.a};
Z.prototype.marshaller=Z.prototype.A;Z.prototype.write=function(a,b){var c=null,d=b||{},c=d.asMapKey||!1,e=this.a.D?!1:this.e;!1===d.marshalTop?c=Y(this.a,a,c,e):(d=this.a,c=JSON.stringify(Y(d,Ab(d,a),c,e)));null!=this.e&&this.e.clear();return c};Z.prototype.write=Z.prototype.write;Z.prototype.w=function(a,b){this.a.o.set(a,b)};Z.prototype.register=Z.prototype.w;var Bb=T;k("transit.reader",function(a,b){if("json"===a||"json-verbose"===a||null==a){var c=new rb(b);return new sb(c,b)}throw Error("Cannot create reader of type "+a);});k("transit.writer",function(a,b){if("json"===a||"json-verbose"===a||null==a){"json-verbose"===a&&(null==b&&(b={}),b.verbose=!0);var c=new tb(b);return new Z(c,b)}c=Error('Type must be "json"');c.data={type:a};throw c;});
k("transit.makeBuilder",function(a){function b(){}b.prototype.init=a.init;b.prototype.add=a.add;b.prototype.finalize=a.finalize;b.prototype.fromArray=a.fromArray;return new b});k("transit.makeWriteHandler",function(a){function b(){}b.prototype.tag=a.tag;b.prototype.rep=a.rep;b.prototype.p=a.stringRep;b.prototype.M=a.getVerboseHandler;return new b});k("transit.date",Ha);k("transit.integer",ya);
k("transit.isInteger",function(a){return a instanceof l?!0:"number"===typeof a&&!isNaN(a)&&Infinity!==a&&parseFloat(a)===parseInt(a)});k("transit.uuid",function(a){return Ga(a)});k("transit.isUUID",function(a){return a instanceof O});k("transit.bigInt",za);k("transit.isBigInt",function(a){return a instanceof J&&"n"===a.tag});k("transit.bigDec",Aa);k("transit.isBigDec",function(a){return a instanceof J&&"f"===a.tag});k("transit.keyword",Da);k("transit.isKeyword",function(a){return a instanceof L});
k("transit.symbol",Ea);k("transit.isSymbol",function(a){return a instanceof N});k("transit.binary",Ia);k("transit.isBinary",function(a){return"undefined"!=typeof Buffer&&a instanceof Buffer?!0:"undefined"!=typeof Uint8Array&&a instanceof Uint8Array?!0:a instanceof J&&"b"===a.tag});k("transit.uri",Ja);k("transit.isURI",function(a){return a instanceof J&&"r"===a.tag});k("transit.map",T);k("transit.isMap",Ma);k("transit.set",Oa);k("transit.isSet",function(a){return a instanceof U});
k("transit.list",Qa);k("transit.isList",function(a){return a instanceof J&&"list"===a.tag});k("transit.quoted",Pa);k("transit.isQuoted",function(a){return a instanceof J&&"'"===a.tag});k("transit.tagged",K);k("transit.isTaggedValue",function(a){return a instanceof J});k("transit.link",Ra);k("transit.isLink",function(a){return a instanceof J&&"link"===a.tag});k("transit.hash",I);k("transit.hashMapLike",ua);k("transit.hashArrayLike",va);k("transit.equals",G);
k("transit.extendToEQ",function(a,b){a.v=b.hashCode;a.s=b.equals;return a});k("transit.mapToObject",function(a){var b={};a.forEach(function(a,d){if("string"!==typeof d)throw Error("Cannot convert map with non-string keys");b[d]=a});return b});k("transit.objectToMap",function(a){var b=Bb(),c;for(c in a)a.hasOwnProperty(c)&&b.set(c,a[c]);return b});k("transit.decoder",function(a){return new W(a)});k("transit.UUIDfromString",Ga);k("transit.randomUUID",{}.P);k("transit.stringableKeys",xb);
k("transit.readCache",function(){return new pa});k("transit.writeCache",function(){return new oa});})();
